'use strict';
// Proposed BitPosClock screens. Fixtures only; no wallet, payment or hardware calls.
const icon = (name, size=24) => {
  const paths={cup:'<path d="M5 8h12v8a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4Z"/><path d="M17 9h2a3 3 0 0 1 0 6h-2M8 3v2m5-2v2M3 22h18"/>',check:'<path d="m5 12 4 4L19 6"/>',gift:'<rect x="3" y="9" width="18" height="4" rx="1"/><path d="M5 13v8h14v-8M12 9v12"/><path d="M12 9C2 9 5 0 9 4l3 5c10 0 7-9 3-5Z"/>',wifi:'<path d="M2 8a16 16 0 0 1 20 0M5 12a11 11 0 0 1 14 0M9 16a5 5 0 0 1 6 0"/><circle cx="12" cy="20" r="1"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',star:'<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/>',alert:'<path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3v1"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',link:'<path d="M9 8 7 6a4 4 0 0 0-6 6l5 5a4 4 0 0 0 6 0l1-1m2-8 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0l-1-1M8 12l8-4"/>'};
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.star}</svg>`;
};
const digits=(value,size=42,tone='')=>`<span class="digits ${tone}" style="font-size:${size}px"><span class="ghost" aria-hidden="true">${value.replace(/[0-9]/g,'8')}</span><span class="lit">${value}</span></span>`;
const qr=()=>{
  let cells='';
  for(let y=0;y<25;y++)for(let x=0;x<25;x++){
    const finder=(x<8&&y<8)||(x>16&&y<8)||(x<8&&y>16);
    if(!finder&&((x*17+y*13+x*y)%7<3))cells+=`<rect x="${x+3}" y="${y+3}" width="1" height="1"/>`;
  }
  const finders=[[3,3],[21,3],[3,21]].map(([x,y])=>`<rect x="${x}" y="${y}" width="7" height="7"/><rect x="${x+1}" y="${y+1}" width="5" height="5" fill="white"/><rect x="${x+2}" y="${y+2}" width="3" height="3"/>`).join('');
  return `<div class="qr"><svg viewBox="0 0 31 31" aria-label="QR ภาพจำลอง สแกนไม่ได้"><rect width="31" height="31" fill="white"/><g fill="#21162f">${cells}${finders}</g><rect x="8" y="12" width="15" height="7" fill="white"/><text x="15.5" y="16.6" text-anchor="middle" font-family="sans-serif" font-size="3" fill="#21162f">DEMO</text></svg></div>`;
};
const button=(label,tone='primary')=>`<div class="device-button ${tone}">${label}</div>`;
const badge=(label,tone='')=>`<span class="badge ${tone}">${label}</span>`;
const rows=(items)=>`<div class="rows">${items.map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join('')}</div>`;
const cupArt=()=>`<svg viewBox="0 0 180 180" class="cup-art" aria-hidden="true"><circle cx="90" cy="82" r="67" fill="#352147"/><path d="M30 114h120M44 102h92M56 57h61v34a20 20 0 0 1-20 20H76a20 20 0 0 1-20-20Z" fill="#d7b76a"/><path d="M117 63h11a14 14 0 0 1 0 28h-11M75 27c-9 7 9 10 0 18m18-22c-9 7 9 10 0 18" fill="none" stroke="#d7b76a" stroke-width="5" stroke-linecap="round"/><circle cx="139" cy="35" r="7" fill="#bfa0ec"/></svg>`;
const payment=(kind)=>`<div class="payment-layout"><div><div class="eyebrow">ORDER #BP-1042</div><h1>${kind==='USDG'?'จ่ายด้วย USDG':'สแกน PromptPay'}</h1><div class="amount">${digits(kind==='USDG'?'3.50':'120.00',39)}<span>${kind==='USDG'?'USDG · SOLANA':'THB'}</span></div><p>ลาเต้เย็น + ครัวซองต์</p>${badge('รอการชำระ', 'warn')}<p class="subtle">${kind==='USDG'?'สแกนดูเมนู แล้วจ่ายใน wallet':'สแกนด้วยแอปธนาคารของคุณ'}</p><div class="device-button secondary">${kind==='USDG'?'สลับเป็น PromptPay':'สลับเป็น USDG'}</div></div><div class="qr-column">${qr()}<small>QR จำลอง · สแกนไม่ได้</small><span class="expiry">${icon('clock',12)} 02:00</span></div></div>`;

const clockScreens=[
  {id:'BPC-01',key:'idle',title:'จอพัก · เวลาและราคา',group:'หน้าร้าน',phase:'4',trigger:'ไม่มี order ที่กำลังชำระ แสดงเวลาและ ticker หมุนสลับกับสื่อของร้าน',contract:'Market feed + timestamp/staleness; ไม่แสดงราคาเก่าว่าเป็น live',next:'BPC-02 / BPC-03',body:()=>`<div class="idle-time"><div class="eyebrow">WEDNESDAY / 07 OCT 2026</div>${digits('10:24',66)}<span>BITPOS CAFE · ยินดีต้อนรับ</span></div><div class="market-strip"><div><span class="lcd">SOL-USDT</span>${digits('148.25',27)}</div><div><b class="up">+2.41%</b><span>ราคาสมมติ · 24h</span></div><svg viewBox="0 0 105 40" width="105" height="40"><path d="M0 34 10 31 20 33 30 22 40 26 50 15 60 19 70 9 80 13 90 5 105 2" fill="none" stroke="#47d7a4" stroke-width="2"/></svg></div>`},
  {id:'BPC-02',key:'promo',title:'จอพัก · เมนูและแคมเปญ',group:'หน้าร้าน',phase:'4 / 6',trigger:'ร้านเผยแพร่แคมเปญแล้ว สลับเมนู / GIF / สื่อหน้าร้านตามตาราง',contract:'Published campaign version + media; AI draft ยังไม่ขึ้นหน้าจอลูกค้า',next:'BPC-03',body:()=>`<div class="promo-layout"><div><div class="eyebrow">YOUR NEXT COFFEE, ON US</div><h1>กาแฟแก้วโปรด<br>พร้อมแต้มแก้วถัดไป</h1><p>จ่ายด้วย USDG บน Solana<br>สะสม 5 ครั้ง รับเครื่องดื่ม 1 แก้ว</p>${badge('ตามเงื่อนไขของร้าน','gold')}${button('สแกนเมนูจาก QR หน้าร้าน')}</div>${cupArt()}</div><div class="media-note">พื้นที่สื่อของร้าน · ภาพนิ่งตัวอย่าง / รองรับ GIF ตาม firmware</div>`},
  {id:'BPC-03',key:'order',title:'รายการสั่งซื้อ',group:'จ่ายเงิน',phase:'2 / 4',trigger:'พนักงานเลือกสินค้าใน POS หรือลูกค้าสั่งจากเว็บ QR',contract:'Order ID + server-priced summary + revision; ไม่เชื่อถือยอดจาก client',next:'BPC-04',body:()=>`<div class="eyebrow">YOUR ORDER / #BP-1042</div><h1>เช็กเมนูก่อนชำระ</h1>${rows([['ลาเต้เย็น × 1','฿70'],['ครัวซองต์ × 1','฿50']])}<div class="total-row"><span>รวมสุทธิ / THB</span>${digits('120.00',34)}</div>${button('เลือกรูปแบบชำระเงิน '+icon('arrow',18))}`},
  {id:'BPC-04',key:'methods',title:'เลือกช่องทางชำระ',group:'จ่ายเงิน',phase:'3 / 4',trigger:'Order พร้อมชำระและยังไม่ paid; แตะเปลี่ยนช่องทางได้',contract:'สร้าง payment attempt แยกแต่ใช้ order เดิม; quote ของช่องทางที่เลือก',next:'BPC-05 / BPC-06 / BPC-07',body:()=>`<div class="eyebrow">ORDER #BP-1042 / 120 THB</div><h1>เลือกวิธีจ่ายของคุณ</h1><div class="method-choices"><div class="method selected"><b>USDG</b><span>Solana · wallet</span>${badge('สะสมแต้ม','gold')}</div><div class="method"><b>PromptPay</b><span>สแกนแอปธนาคาร</span></div><div class="method"><b>เงินสด</b><span>ชำระกับพนักงาน</span></div></div><p class="subtle">สิทธิ์ของแคมเปญอาจต่างกันตามช่องทาง</p>${button('ต่อไป '+icon('arrow',18))}`},
  {id:'BPC-05',key:'usdg',title:'QR · USDG / Solana Blink',group:'จ่ายเงิน',phase:'3 / 4',trigger:'Server สร้าง canonical USDG quote และ Action URL สำหรับ order',contract:'Mint/program/network/recipient/amount/order reference + expiry; หน้าเว็บเมนูเป็น fallback',next:'BPC-08 / BPC-15',body:()=>payment('USDG')},
  {id:'BPC-06',key:'promptpay',title:'QR · PromptPay',group:'จ่ายเงิน',phase:'3 / 4',trigger:'Server สร้าง Stripe PromptPay attempt สำหรับ order เดิม',contract:'Provider QR + amount/expiry; เปลี่ยน paid หลัง verified webhook เท่านั้น',next:'BPC-08 / BPC-15',body:()=>payment('PromptPay')},
  {id:'BPC-07',key:'cash',title:'เงินสด · รอพนักงาน',group:'จ่ายเงิน',phase:'1 / 3 / 4',trigger:'เลือกเงินสด; พนักงานรับเงินและยืนยันตามสิทธิ์ POS',contract:'Authenticated cashier confirmation + paid event; ลูกค้ากดยืนยันเองไม่ได้',next:'BPC-09',body:()=>`<div class="center-state"><div class="status-icon">${icon('cup',40)}</div><h1>ชำระเงินที่เคาน์เตอร์</h1><div class="amount horizontal">${digits('120.00',43)}<span>THB</span></div><p>รับเงิน ฿200 · เงินทอน ฿80</p>${badge('รอพนักงานยืนยัน','warn')}<p class="subtle">รับใบเสร็จและสิทธิ์ตามเงื่อนไขร้าน</p></div>`},
  {id:'BPC-08',key:'confirming',title:'กำลังตรวจสอบการชำระ',group:'จ่ายเงิน',phase:'3 / 4',trigger:'พบ signature / provider event และ backend กำลัง verify',contract:'ยังไม่เป็น paid จนตรวจสำเร็จ; callback/signature อย่างเดียวไม่พอ',next:'BPC-09 / BPC-15',body:()=>`<div class="center-state"><div class="status-icon">${icon('clock',42)}</div><h1>กำลังตรวจสอบการชำระ</h1><p>USDG · Order #BP-1042</p><div class="progress-dots"><i></i><i></i><i></i></div><p>โปรดรอสักครู่ ไม่ต้องจ่ายซ้ำ</p><span class="subtle">จอจะแจ้งเมื่อร้านได้รับการยืนยัน</span></div>`},
  {id:'BPC-09',key:'paid',title:'ชำระสำเร็จ · เสียงและสถานะ',group:'จ่ายเงิน',phase:'3 / 4',trigger:'Backend ยืนยัน paid และส่ง event ที่มี order/event IDs',contract:'Durable outbox → terminal render ACK; เสียงครั้งเดียวต่อ event; reward แยกสถานะ',next:'BPC-10 / BPC-14',body:()=>`<div class="center-state"><div class="status-icon success">${icon('check',44)}</div><h1>ชำระเงินสำเร็จ</h1><div class="amount horizontal">${digits('120.00',38)}<span>THB</span></div><p>ขอบคุณครับ · Order #BP-1042</p>${badge('รับเงินแล้ว','ok')}<div class="receipt-line">${icon('gift',16)} กำลังเตรียมสิทธิ์สะสมของคุณ</div></div>`},
  {id:'BPC-10',key:'claim',title:'QR · รับสิทธิ์หลังจ่าย',group:'รางวัล',phase:'5',trigger:'Paid order มี eligible reward และต้อง claim/bind wallet ตาม policy',contract:'Receipt/session + wallet ownership; QR เพียงอย่างเดียวห้ามแย่งสิทธิ์ผู้จ่าย',next:'BPC-11 / BPC-12',body:()=>`<div class="payment-layout"><div><div class="eyebrow">PAID / #BP-1042</div><h1>รับแต้มของคุณ</h1><p>สแกนดูสิทธิ์ แล้วเชื่อม wallet<br>กับใบเสร็จของคุณ</p><div class="reward-mini">${icon('gift',29)}<div><b>1 สิทธิ์สะสม</b><small>แคมเปญ Coffee on Solana</small></div></div>${badge('ชำระสำเร็จแล้ว','ok')}<p class="subtle">ต้องยืนยันว่าเป็นเจ้าของใบเสร็จ</p></div><div class="qr-column">${qr()}<small>QR จำลอง · สแกนไม่ได้</small></div></div>`},
  {id:'BPC-11',key:'collectible',title:'เปิดรางวัล · NFT สุ่ม',group:'รางวัล',phase:'5',trigger:'Backend grant/issuance สำเร็จและมีผลสุ่มที่ตรวจย้อนหลังได้',contract:'Server-authoritative outcome; แสดง issued เมื่อ mint/ownership proof ผ่าน policy เท่านั้น',next:'BPC-12',body:()=>`<div class="collect-layout"><div class="collect-card">${cupArt()}<span>ESPRESSO DAWN</span><small>ART CONCEPT 01 / 05</small></div><div><div class="eyebrow gold-text">YOUR COLLECTIBLE</div><h1>แก้วนี้มีของสะสม</h1><p>Espresso Dawn<br>หนึ่งใน NFT 5 แบบของร้าน</p>${badge('ตัวอย่างเมื่อออกสิทธิ์สำเร็จ','gold')}<p class="subtle">ส่งเข้ากระเป๋าที่ผูกกับใบเสร็จ<br>wal…DEMO · ไม่มีการ mint จริง</p>${button('ดูคอลเลกชัน','gold-button')}</div></div>`},
  {id:'BPC-12',key:'loyalty',title:'สะสมแต้ม · ระดับรางวัล',group:'รางวัล',phase:'5',trigger:'Points ledger ของ wallet/customer ที่ผูกถูกต้องเปลี่ยนแล้ว',contract:'Campaign version + eligible paid grants; tier และ cost ใช้ server policy',next:'BPC-13',body:()=>`<div class="eyebrow">COFFEE ON SOLANA / YOUR PROGRESS</div><h1>อีก 2 ครั้ง ได้แก้วถัดไป</h1><div class="stamp-row">${[1,2,3,4,5].map(n=>`<div class="stamp ${n<=3?'filled':''}">${n<=3?icon('cup',28):n}</div>`).join('')}</div><div class="tier-row"><div><b>5 ครั้ง</b><span>Voucher เครื่องดื่ม</span></div><div><b>10 ครั้ง</b><span>NFT รุ่นพิเศษ</span></div><div><b>20 ครั้ง</b><span>ตุ๊กตาของร้าน</span></div></div><p class="subtle">ตัวอย่าง policy · แลกตาม stock / เงื่อนไขร้าน</p>`},
  {id:'BPC-13',key:'redeem',title:'Voucher · แลกรางวัลแล้ว',group:'รางวัล',phase:'5',trigger:'พนักงานยืนยัน redeem ของสิทธิ์ที่ยังไม่ถูกใช้ด้วย authenticated action',contract:'Atomic redemption + inventory/fulfillment; NFT ownership ไม่ได้แปลว่า redeem แล้ว',next:'BPC-01',body:()=>`<div class="center-state"><div class="status-icon gold-icon">${icon('gift',40)}</div><h1>แลกเครื่องดื่มแล้ว</h1><p>1 แก้ว · รับได้ที่เคาน์เตอร์</p><div class="voucher-code">VOUCHER DEMO-042</div>${badge('สิทธิ์นี้ใช้แล้ว','gold')}<p class="subtle">ใช้สิทธิ์เดิมซ้ำไม่ได้ · ขอบคุณที่กลับมา</p></div>`},
  {id:'BPC-14',key:'reward-pending',title:'รับเงินแล้ว · รางวัลรอดำเนินการ',group:'กู้คืน / ตั้งค่า',phase:'5',trigger:'Payment paid แต่ mint/issuance ไม่สำเร็จหรือ worker จะ retry',contract:'Persist grant status/retry; ห้ามเปลี่ยน paid เป็น unpaid หรือให้ลูกค้าจ่ายซ้ำ',next:'BPC-11 หลัง retry สำเร็จ',body:()=>`<div class="center-state"><div class="status-icon gold-icon">${icon('clock',42)}</div><h1>รับเงินแล้ว รางวัลกำลังมา</h1><p>คำสั่งซื้อของคุณสำเร็จแล้ว<br>เรากำลังออกสิทธิ์ให้ wallet ที่ผูกไว้</p>${badge('รางวัลรอดำเนินการ','warn')}<div class="receipt-line">ดูสถานะจากใบเสร็จ / หน้า loyalty</div><p class="subtle">ไม่ต้องชำระเงินอีกครั้ง</p></div>`},
  {id:'BPC-15',key:'failed',title:'ชำระไม่สำเร็จ / QR หมดอายุ',group:'กู้คืน / ตั้งค่า',phase:'3 / 4',trigger:'Attempt ล้มเหลว / หมดอายุและ backend ยังไม่พบ verified payment',contract:'Resync ก่อน retry; late settlement มี reconciliation; ไม่ได้รางวัลก่อน paid',next:'BPC-04',body:()=>`<div class="center-state"><div class="status-icon danger">${icon('alert',37)}</div><h1>QR นี้หมดอายุแล้ว</h1><p>ยังไม่ได้รับการยืนยันการชำระ</p>${button('ขอ QR ใหม่','secondary')}<p class="subtle">หากแอปแสดงว่าหักเงินแล้ว ให้แจ้งพนักงาน<br>เราจะตรวจสถานะก่อนเริ่มรายการใหม่</p></div>`},
  {id:'BPC-16',key:'offline',title:'ขาดการเชื่อมต่อ / รอ resync',group:'กู้คืน / ตั้งค่า',phase:'4',trigger:'Transport ขาดการเชื่อมต่อ; เก็บ last known order และ sequence',contract:'Reconnect + authenticated snapshot/event replay/dedup; ไม่เสียงซ้ำและไม่สรุป paid เอง',next:'สถานะล่าสุดหลัง resync',body:()=>`<div class="center-state"><div class="status-icon danger">${icon('wifi',42)}</div><h1>จอขาดการเชื่อมต่อ</h1><p>กำลังเชื่อมต่อร้านอีกครั้ง</p><div class="offline-order"><span>Order #BP-1042</span><b>รอตรวจสถานะล่าสุด</b></div><p class="subtle">หากชำระแล้ว ไม่ต้องจ่ายซ้ำ<br>พนักงานตรวจสถานะจาก POS ได้</p></div>`},
  {id:'BPC-17',key:'wifi',title:'แคมเปญ · สิทธิ์ Wi-Fi',group:'หน้าร้าน',phase:'7',trigger:'ร้านเลือก Wi-Fi เป็น reward ของ paid order/check-in ที่ผ่าน eligibility',contract:'Owner-published rule + bound customer receipt; code TTL + opt-in visibility',next:'BPC-01',body:()=>`<div class="center-state"><div class="status-icon">${icon('wifi',42)}</div><h1>ยินดีต้อนรับนั่งทำงาน</h1><p>สิทธิ์ Wi-Fi หลังทำรายการสำเร็จ</p><div class="wifi-code"><span>BITPOS-GUEST / DEMO</span><b>DEMO-ONLY</b></div><p class="subtle">ตัวอย่างรหัส · ไม่ใช่ Wi-Fi จริง<br>รับรายละเอียดส่วนตัวผ่านหน้าใบเสร็จ</p></div>`},
  {id:'BPC-18',key:'settings',title:'ตั้งค่าเครื่อง / ผูกร้าน',group:'กู้คืน / ตั้งค่า',phase:'1B / 4 / 7',trigger:'Owner/pairing เปิดการตั้งค่าเครื่อง หลังยืนยันสิทธิ์และ device/store binding',contract:'Independent BitPOS namespace/provisioning/config/OTA; ไม่มี credentials ใน UI',next:'BPC-01 หลังพร้อม',body:()=>`<div class="eyebrow">DEVICE SETTINGS / OWNER ACCESS</div><h1>BitPosClock ของร้าน</h1>${rows([['ร้านที่ผูก','BitPOS Cafe · DEMO'],['การเชื่อมต่อ','Wi-Fi / MQTT'],['ความสว่าง / ระดับเสียง','70% / 40%'],['ช่วงงดเสียง','21:00–08:00']])}<div class="settings-actions">${button('ผูกร้าน / จัดการผ่าน POS','secondary')}${badge('Design prototype')}</div>`}
];
window.BitPosClock={screens:clockScreens,icon};
