import {randomUUID,randomBytes} from 'node:crypto';
import {hash,MINT,TOKEN_PROGRAM} from '../packages/domain/src/index';
import type {CounterCreate,DeviceCommand,Quote,DeviceCommandResult,DeviceResultValue} from '../packages/contracts/src/index';
import type {DeviceActor} from '../apps/api/src/device-commands';
import type pg from 'pg';
import assert from 'node:assert/strict';
// Intentional loading boundary: opt-in fixtures must not load required private config when skipped.
export async function tableFixture(stock=100){
 const {pool,tenant}=await import('../apps/api/src/db');const {registry}=await import('../apps/api/src/registry');const {publishPrices}=await import('../apps/api/src/catalog');const {counterQuote,createRoutedOrder}=await import('../apps/api/src/orders');const {applyDeviceCommand}=await import('../apps/api/src/device-commands');
 const merchant=randomUUID(),other=randomUUID(),actor=randomUUID(),product=randomUUID();await pool.query('INSERT INTO merchants(id,name,treasury) VALUES($1,\'Table backend fixture\',\'11111111111111111111111111111111\'),($2,\'Other fixture\',\'11111111111111111111111111111111\')',[merchant,other]);await tenant(merchant,db=>db.query('INSERT INTO products(id,merchant_id,name,name_en,emoji,price_minor,stock) VALUES($1,$2,\'กาแฟ\',\'Coffee\',\'\',3500,$3)',[product,merchant,stock]));
 async function reg(path:string,method:string,input?:unknown,role='owner'){return tenant(merchant,db=>registry(db,merchant,actor,role,path,method,input));}
 const table=await reg('/api/tables','POST',{label:'Table 4'});const a=await reg('/api/devices','POST',{label:'A'});const b=await reg('/api/devices','POST',{label:'B',tableId:table.id});const c=await reg('/api/devices','POST',{label:'C'});const register=await reg('/api/registers','POST',{label:'R'});
 const credentials=new Map<string,string>();const devices=new Map<string,DeviceActor>();for(const device of [a,b,c]){const credential=await reg('/api/devices/'+device.id+'/credential','POST',{});credentials.set(device.id,credential.deviceToken);const connectionId=randomUUID();await tenant(merchant,db=>db.query("UPDATE device_presence SET connection_generation=1,connection_id=$2,connected_until=clock_timestamp()+interval '1 hour' WHERE device_id=$1",[device.id,connectionId]));devices.set(device.id,{merchant,device:device.id,tokenHash:hash(credential.deviceToken),authGeneration:credential.authGeneration,connectionGeneration:'1',connectionId});}
 await reg('/api/registers/'+register.id+'/pairing','PUT',{deviceId:a.id,expectedPairingGeneration:'1'});
 const configuration={expectedRevision:'0',catalogCurrency:'USD' as const,provenance:{kind:'demo_configured' as const,label:'UNIT TEST ONLY'},prices:[{productId:product,unitMinor:'270'}],settlement:{asset:'USDG' as const,network:'solana:devnet' as const,mint:MINT,tokenProgram:TOKEN_PROGRAM,decimals:6 as const,quotePolicy:'USD_CENTS_TO_USDG_1_TO_1' as const}};const pricing=await tenant(merchant,db=>publishPrices(db,merchant,actor,'owner',configuration));
 async function quote(qty=1){return tenant(merchant,db=>counterQuote(db,merchant,register.id,{items:[{productId:product,qty}],serving:{kind:'counter'}}));}
 function input(q:Quote,key:string=randomUUID()):CounterCreate{return {items:q.lines.map(l=>({productId:l.productId,qty:l.qty})),serving:{kind:'counter'},quoteId:q.id,priceVersion:q.priceVersion,idempotencyKey:key};}
 async function create(q:Quote,key?:string){return tenant(merchant,db=>createRoutedOrder(db,merchant,'register',register.id,input(q,key)));}
 async function command(device:string,body:Omit<DeviceCommand,'schemaVersion'|'requestId'|'connectionGeneration'>|Record<string,unknown>,requestId=randomUUID()){const a=devices.get(device);assert.ok(a);const c={schemaVersion:2,requestId,connectionGeneration:a.connectionGeneration,...body};const {commandSchema}=await import('../apps/api/src/device-commands');return tenant(merchant,db=>applyDeviceCommand(db,a,commandSchema.parse(c),new Date().toISOString()));}
 return {pool,tenant,merchant,other,actor,product,table,a,b,c,register,reg,configuration,pricing,credentials,devices,quote,input,create,command};
}
export async function staffToken(pool:pg.Pool,merchant:string,actor:string,role='owner'){const token=randomBytes(32).toString('base64url');await pool.query('INSERT INTO members(user_id,merchant_id,role) VALUES($1,$2,$3) ON CONFLICT(user_id,merchant_id) DO UPDATE SET role=$3',[actor,merchant,role]);await pool.query("INSERT INTO sessions(token_hash,user_id,merchant_id,role,expires_at) VALUES($1,$2,$3,$4,now()+interval '1 hour')",[hash(token),actor,merchant,role]);return token;}
export function success(receipt:DeviceCommandResult):DeviceResultValue {assert.ok(receipt.result.ok,JSON.stringify(receipt.result));return receipt.result.value;}
