import MerchantIcon from './MerchantIcon';
import React, { useEffect, useRef, useState } from 'react';
import { api, errorMessage } from '../lib/api';
import { WalletAvatar } from './Payment';
import OrderBill from './OrderBill';
import type { PrivateOrder, Session } from '../lib/table';
export interface Customer { id: string; name?: string; phone?: string; email?: string; notes?: string; wallets: { address: string; avatar: string }[] }
const blankContact = { name: '', phone: '', email: '', notes: '' };
export default function CustomerCard({ session, customerId, disabled, language, select }: { session: Session; customerId: string; disabled: boolean; language: 'en' | 'th'; select(id: string): Promise<void> }) {
  const [customers, setCustomers] = useState<Customer[]>([]); const [contact, setContact] = useState(blankContact); const [editing, setEditing] = useState(false); const [history, setHistory] = useState<PrivateOrder[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const working = useRef(false);
  const selected = customers.find(customer => customer.id === customerId);
  const text = (th: string, en: string) => language === 'th' ? th : en;
  useEffect(() => { let active = true; void api<{ customers: Customer[] }>('/customers', undefined, session.token).then(next => { if (active) setCustomers(next.customers); }).catch(error => { if (active) setError(error instanceof Error ? error.message : 'Customers unavailable'); }); return () => { active = false; }; }, [session.token]);
  useEffect(() => { setHistory([]); setEditing(false); }, [customerId]);
  async function act(run: () => Promise<void>) { if (working.current) return; working.current = true; setBusy(true); setError(''); try { await run(); } catch (error) { setError(errorMessage(error)); } finally { working.current = false; setBusy(false); } }
  return <section className="customer-card"><h3>{text('ลูกค้า', 'Customer')}</h3><select aria-label="Customer" value={customerId} disabled={disabled || busy} onChange={event => void act(() => select(event.target.value))}><option value="">{text('บุคคลทั่วไป (ไม่เก็บข้อมูลติดต่อ)', 'Walk-in customer')}</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.name || 'Guest'} · {customer.id.slice(0, 8)}</option>)}</select>{selected && <><p>{selected.name || 'Guest'}<small>{selected.phone} {selected.email}</small></p>{selected.wallets.map(wallet => <div className="wallet" key={wallet.address}><WalletAvatar address={wallet.address} /><details className="customer-wallet-details"><summary><span className="mono">{wallet.address.slice(0,6)}...{wallet.address.slice(-4)}</span></summary><span className="mono">{wallet.address}</span></details></div>)}<div className="toolbar"><button className="secondary" disabled={busy} onClick={() => { setContact({ name: selected.name || '', phone: selected.phone || '', email: selected.email || '', notes: selected.notes || '' }); setEditing(true); }}><MerchantIcon name="edit" />Edit contact</button><button className="secondary" disabled={busy} onClick={() => void act(async () => { const next = await api<{ orders: PrivateOrder[] }>(`/customers/${encodeURIComponent(selected.id)}/history`, undefined, session.token); setHistory(next.orders); })}><MerchantIcon name="arrow" />History</button></div></>}
    <button className="secondary" disabled={disabled || busy} onClick={() => void act(async () => { await select(''); setContact(blankContact); setEditing(true); })}><MerchantIcon name="staff" />Add customer details</button>{editing && <form onSubmit={event => { event.preventDefault(); void act(async () => { const saved = await api<Customer>(selected ? `/customers/${encodeURIComponent(selected.id)}` : '/customers', contact, session.token, selected ? 'PATCH' : 'POST'); const next = await api<{ customers: Customer[] }>('/customers', undefined, session.token); setCustomers(next.customers); if (!disabled) await select(saved.id); setEditing(false); }); }}>{Object.entries(contact).map(([field, value]) => <label key={field}>{field}<input type={field === 'email' ? 'email' : field === 'phone' ? 'tel' : 'text'} value={value} onChange={event => setContact(current => ({ ...current, [field]: event.target.value }))} /></label>)}<small>All details are optional.</small><button disabled={busy}><MerchantIcon name="save" />Save contact</button><button type="button" className="secondary" onClick={() => setEditing(false)}><MerchantIcon name="close" />Cancel</button></form>}
    {history.map(past => <details className="history" key={past.id}><summary>{past.id.slice(0, 8)} · {past.pricing.total.currency} · {past.status}</summary><OrderBill order={past} language={language} /></details>)}{error && <p className="error" role="alert">{error}</p>}
  </section>;
}
