import {useEffect,useRef,useState} from 'react';
import type {PrivateOrder} from '../lib/table';
import {formatMoney} from '../lib/money';
import MerchantIcon from './MerchantIcon';
import OrderBill from './OrderBill';
import '../styles/incoming.css';
type Group='all'|'waiting'|'paid'|'closed'|'attention';
function group(order:PrivateOrder):Group{return order.status==='PAID'?'paid':order.status==='EXPIRED'?'closed':order.status==='RECOVERY'?'attention':'waiting';}
export default function IncomingOrders({orders,detail,error,busy,language,canReview,select,close,refresh,review}:{orders:PrivateOrder[];detail?:PrivateOrder;error:string;busy:boolean;language:'en'|'th';canReview:boolean;select:(id:string)=>void;close:()=>void;refresh:()=>void;review:()=>void}){
 const text=(th:string,en:string)=>language==='th'?th:en;
 const [category,setCategory]=useState<Group>('all'),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const detailRef=useRef<HTMLElement>(null),selectedButton=useRef<HTMLButtonElement|null>(null);
 const groups:{id:Group;label:string}[]=[{id:'all',label:text('ทั้งหมด','All')},{id:'waiting',label:text('รอชำระ','Awaiting payment')},{id:'paid',label:text('ชำระแล้ว','Paid')},{id:'closed',label:text('ปิดแล้ว','Closed')},{id:'attention',label:text('ต้องตรวจสอบ','Needs attention')}];
 const filtered=orders.filter(o=>(category==='all'||group(o)===category)&&[o.id,o.authority.serving.label,...o.pricing.lines.map(l=>`${l.name} ${l.nameEn}`)].join(' ').toLowerCase().includes(search.trim().toLowerCase()));
 const pages=Math.max(1,Math.ceil(filtered.length/12)),current=Math.min(page,pages-1),visible=filtered.slice(current*12,current*12+12);
 useEffect(()=>setPage(0),[category,search]);
 useEffect(()=>{if(detail){detailRef.current?.focus();}else{selectedButton.current?.focus();}},[detail?.id]);
 useEffect(()=>{if(!detail)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[detail?.id,close]);
 const label=(o:PrivateOrder)=>o.closureReason==='canceled'?text('ยกเลิกแล้ว','Canceled'):o.status==='PAID'?text('ชำระแล้ว','Paid'):o.status==='EXPIRED'?text('หมดเวลา','Expired'):o.status==='RECOVERY'?text('ต้องตรวจสอบ','Needs attention'):o.status==='CONFIRMING'?text('กำลังยืนยัน','Confirming'):text('รอชำระ','Awaiting payment');
 const payable=detail&&['AWAITING_WALLET','AWAITING_PAYMENT'].includes(detail.status)&&Date.parse(detail.quoteExpiresAt)>Date.now();
 return <main className={`incoming-workspace incoming-board ${detail?'has-detail':''}`}>
  <section className="panel incoming-browser" aria-label={text('รายการออร์เดอร์','Order list')}>
   <div className="incoming-heading"><div><h1>{text('รายการออร์เดอร์','Incoming orders')}</h1><p>{text('ออร์เดอร์จากเคาน์เตอร์และโต๊ะ','Counter and table orders')}</p></div><button className="secondary" disabled={busy} onClick={refresh}><MerchantIcon name="refresh"/>{text('รีเฟรช','Refresh')}</button></div>
   <nav className="order-filters" aria-label={text('กรองสถานะออร์เดอร์','Order status filters')}>{groups.map(g=><button key={g.id} type="button" aria-pressed={category===g.id} onClick={()=>setCategory(g.id)}>{g.label}<span>{g.id==='all'?orders.length:orders.filter(o=>group(o)===g.id).length}</span></button>)}</nav>
   <label className="order-search"><span>{text('ค้นหาออร์เดอร์','Search orders')}</span><input type="search" value={search} placeholder={text('เลขบิล โต๊ะ หรือชื่อเมนู','Order number, table or menu item')} onChange={e=>setSearch(e.target.value)}/></label>
   {error&&<p className="error" role="status">{text('อัปเดตไม่สำเร็จ กดรีเฟรชเพื่อลองใหม่','Could not update. Refresh to try again.')}<details><summary>{text('รายละเอียด','Details')}</summary>{error}</details></p>}
   <div className="incoming-list">{visible.map(o=><button className={`incoming-row order-row ${detail?.id===o.id?'is-selected':''}`} key={o.id} disabled={busy} aria-label={`${text('ดูออร์เดอร์','View order')} ${o.id.slice(0,8)}`} aria-pressed={detail?.id===o.id} onClick={e=>{selectedButton.current=e.currentTarget;select(o.id);}}><span className="order-row-main"><strong>{o.authority.serving.label}</strong><span className="order-items-preview">{o.pricing.lines.slice(0,2).map(l=>`${l.qty} × ${language==='th'?l.name:l.nameEn||l.name}`).join(' · ')}{o.pricing.lines.length>2?` +${o.pricing.lines.length-2}`:''}</span><small>#{o.id.slice(0,8)}{o.createdAt&&<> · <time dateTime={o.createdAt}>{new Date(o.createdAt).toLocaleString(language==='th'?'th-TH':'en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time></>}</small></span><span className="order-row-end"><strong>{formatMoney(o.pricing.total)}</strong><span className={`order-state state-${group(o)}`}>{label(o)}</span></span></button>)}</div>
   {!filtered.length&&<div className="orders-empty"><MerchantIcon name="receipt"/><h2>{search||category!=='all'?text('ไม่พบออร์เดอร์','No matching orders'):text('ยังไม่มีออร์เดอร์','No orders yet')}</h2><p>{text('ออร์เดอร์ใหม่จะแสดงที่นี่','New orders appear here.')}</p>{(search||category!=='all')&&<button className="secondary" onClick={()=>{setSearch('');setCategory('all');}}>{text('ล้างตัวกรอง','Clear filters')}</button>}</div>}
   {!!filtered.length&&<div className="order-pagination"><small>{current*12+1}–{Math.min((current+1)*12,filtered.length)} / {filtered.length}</small><div><button className="secondary" disabled={current===0} onClick={()=>setPage(current-1)}>{text('ก่อนหน้า','Previous')}</button><button className="secondary" disabled={current+1>=pages} onClick={()=>setPage(current+1)}>{text('ถัดไป','Next')}</button></div></div>}
   <small className="orders-scope">{text('แสดงสูงสุด 200 ออร์เดอร์ล่าสุด','Showing up to 200 most recent orders')}</small>
  </section>
  {detail?<section className="panel incoming-detail" ref={detailRef} tabIndex={-1} aria-label={text('รายละเอียดออร์เดอร์','Order details')}><div className="incoming-detail-heading"><h2>{text('รายละเอียดบิล','Order details')}</h2><button className="secondary" aria-label={text('ปิดรายละเอียด','Close order details')} onClick={close}><MerchantIcon name="close"/></button></div><OrderBill order={detail} language={language}/><div className="incoming-actions"><a className={payable?'button':'button secondary'} href={detail.paymentUrl} target="_blank" rel="noopener noreferrer"><MerchantIcon name={payable?'arrow':'receipt'}/>{payable?text('เปิดหน้าชำระ','Open checkout'):detail.status==='PAID'?text('ดูใบเสร็จ','View receipt'):text('ดูหน้าบิล','View bill')}<span className="new-window-hint"> ↗</span></a>{detail.status==='RECOVERY'&&canReview&&<details className="bill-details"><summary>{text('จัดการรายการที่ต้องตรวจสอบ','Review payment issue')}</summary><p>{text('ตรวจสอบธุรกรรมก่อนยืนยัน ขั้นตอนนี้ไม่คืนเงินหรือเปลี่ยนบิลเป็นชำระแล้ว','Check the transaction first. This does not refund or mark the bill paid.')}</p><button disabled={busy} onClick={()=>{if(window.confirm(text('ยืนยันว่าตรวจสอบรายการนี้แล้ว?','Confirm that you have checked this payment?')))review();}}><MerchantIcon name="check"/>{text('ยืนยันการตรวจสอบ','Mark issue reviewed')}</button></details>}</div></section>:<aside className="panel incoming-placeholder"><MerchantIcon name="receipt"/><h2>{text('เลือกออร์เดอร์','Select an order')}</h2><p>{text('ดูรายการอาหาร ยอดรวม และสถานะที่นี่','View items, total and payment status here.')}</p></aside>}
 </main>;
}
