import React from 'react';
import type { OrderView, Settlement } from '../../../../packages/contracts/src/index';
import { formatMoney, lineTotal } from '../lib/money';

export function SettlementTrust({ settlement }: { settlement: Settlement }) {
  return <section className="notice trust" aria-label="Settlement trust"><strong>{formatMoney(settlement)} · test USDG, not redeemable money</strong><p>{settlement.network} · Merchant-funded network fee sponsor (network fees still exist).</p><dl><dt>Mint</dt><dd className="mono">{settlement.mint}</dd><dt>Token program</dt><dd className="mono">{settlement.tokenProgram}</dd><dt>Genesis</dt><dd className="mono">{settlement.genesisHash}</dd><dt>Recipient</dt><dd className="mono">{settlement.recipient}</dd></dl></section>;
}
export function FrozenRouting({ authority }: { authority: OrderView['authority'] }) {
  return <dl className="routing"><dt>Serving</dt><dd>{authority.serving.label}</dd><dt>Source</dt><dd>{authority.source.kind === 'register' ? 'Tablet / register' : authority.source.kind === 'device' ? 'Table device' : 'Legacy counter'} · {authority.source.label}</dd><dt>Display target</dt><dd className="mono">{authority.kind === 'versioned' ? authority.target.deviceId : authority.target.legacyTerminalId}</dd>{authority.kind === 'versioned' && <><dt>Frozen generations</dt><dd>Assignment {authority.target.assignmentGeneration} · Pairing {authority.pairingGeneration ?? 'Independent device'}</dd></>}</dl>;
}
export default function OrderBill({ order, language = 'en', publicView = false, customer = false }: { order: OrderView; language?: 'en' | 'th'; publicView?: boolean; customer?: boolean }) {
  if (customer) return <section aria-label="Your order"><ul className="checkout-lines">{order.pricing.lines.map(line => <li key={line.productId}><span><span className="checkout-quantity">{line.qty} ×</span> {line.nameEn || line.name}</span><strong>{formatMoney(lineTotal(line))}</strong></li>)}</ul></section>;
  const status = order.closureReason === 'canceled' ? 'Canceled' : ({ AWAITING_WALLET: 'Awaiting payment', AWAITING_PAYMENT: 'Awaiting payment', CONFIRMING: 'Confirming payment', PAID: 'Paid', EXPIRED: 'Expired', RECOVERY: 'Needs attention' } as Record<string,string>)[order.status] || order.status;
  return <section aria-label="Order bill"><p className="bill-reference">#{order.id.slice(0,8)} · {order.authority.serving.label}</p><ul className="bill">{order.pricing.lines.map(line => <li key={line.productId}><span>{line.qty} × {language === 'th' ? line.name : line.nameEn || line.name}</span><strong>{formatMoney(lineTotal(line))}</strong></li>)}</ul><div className="total"><span>{language === 'th' ? 'ยอดรวม' : 'Total'}</span><strong>{formatMoney(order.pricing.total)}</strong></div><p className={`status ${order.status.toLowerCase()}`} role="status">{status}</p><p className="bill-network">Devnet · test USDG · Network fee covered by the store</p><details className="bill-details"><summary>{language === 'th' ? 'รายละเอียดธุรกรรม' : 'Payment details'}</summary><p className="mono">Order: {order.id}</p><ul className="bill">{order.pricing.lines.map(line=><li key={line.productId}><span>{language==='th'?line.name:line.nameEn||line.name}</span><span>{formatMoney(line.unitPrice)} {language==='th'?'ต่อชิ้น':'each'}</span></li>)}</ul>{!publicView && <FrozenRouting authority={order.authority} />}<SettlementTrust settlement={order.settlement} /></details></section>;
}
