import ShopFloor from './ShopFloor';
import MerchantIcon from './MerchantIcon';
import React, { useRef, useState } from 'react';
import { api, errorMessage } from '../lib/api';
import type { Device, Register, Session, Table } from '../lib/table';

export default function RegistrySettings({ session, tables, devices, registers, refresh }: { session: Session; tables: Table[]; devices: Device[]; registers: Register[]; refresh(): Promise<void> }) {
  const [busy, setBusy] = useState(false); const working = useRef(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [credential, setCredential] = useState<{ deviceId: string; deviceToken: string; authGeneration: string }>();
  const editable = session.role === 'owner' || session.role === 'manager';
  async function act(run: () => Promise<void>) {
    if (working.current) return;
    working.current = true; setBusy(true); setError(''); setMessage('');
    try { await run(); setMessage('Saved.'); await refresh(); }
    catch (error) { setError(errorMessage(error)); }
    finally { working.current = false; setBusy(false); }
  }
  return <section className="panel registry" aria-label="Device and table registry"><ShopFloor merchantId={session.merchantId} tables={tables} devices={devices} editable={editable} assign={async(device,tableId)=>{await api(`/devices/${encodeURIComponent(device.id)}`,{tableId,expectedAssignmentGeneration:device.assignmentGeneration},session.token,'PATCH');await refresh();}}/><details className="floor-manage"><summary><MerchantIcon name="plus"/>Manage tables, devices & connections</summary><h2>Tables & POSClock</h2><p>Assign a table to each POSClock and connect one POSClock to each register.</p><button className="secondary" disabled={busy} onClick={() => void act(refresh)}><MerchantIcon name="arrow" />Refresh</button>
    {editable && <div className="registry-grid">{(['tables', 'devices', 'registers'] as const).map(kind => <form key={kind} onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); void act(async () => { await api(`/${kind}`, { label: data.get('label') }, session.token); form.reset(); }); }}><h3>Register {kind === 'tables' ? 'table' : kind === 'devices' ? 'device' : 'Tablet register'}</h3><label>Name<input name="label" required maxLength={95} /></label><button disabled={busy}><MerchantIcon name="plus" />Create {kind === 'tables' ? 'table' : kind === 'devices' ? 'device' : 'register'}</button></form>)}</div>}
    <h3>Tables</h3>{tables.map(table => <form className="registry-row" key={`${table.id}:${table.label}:${table.retiredAt}`} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void act(async () => { await api(`/tables/${encodeURIComponent(table.id)}`, { label: data.get('label') }, session.token, 'PATCH'); }); }}><label>Table label<input name="label" defaultValue={table.label} readOnly={!editable || !!table.retiredAt} required maxLength={95} /></label><span className="badge">{table.retiredAt ? 'Retired' : 'Active'}</span>{editable && !table.retiredAt && <><button disabled={busy}><MerchantIcon name="save" />Save table label</button><button type="button" className="secondary" disabled={busy} onClick={() => void act(async () => { await api(`/tables/${encodeURIComponent(table.id)}`, { retired: true }, session.token, 'PATCH'); })}><MerchantIcon name="arrow" />Retire table</button></>}</form>)}
    <h3>Devices</h3>{devices.map(device => <form className="registry-row" key={`${device.id}:${device.assignmentGeneration}:${device.label}:${device.revokedAt}`} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void act(async () => { await api(`/devices/${encodeURIComponent(device.id)}`, { label: data.get('label'), tableId: data.get('tableId') || null, expectedAssignmentGeneration: device.assignmentGeneration }, session.token, 'PATCH'); }); }}><label>Device label<input name="label" defaultValue={device.label} readOnly={!editable} required maxLength={95} /></label><label>Assigned table<select aria-label="Assigned table" name="tableId" defaultValue={device.tableId ?? ''} disabled={!editable || busy || !!device.revokedAt}><option value="">No table / counter</option>{tables.filter(t => !t.retiredAt).map(t => <option key={t.id} value={t.id}>{t.label}</option>)}</select></label><details className="bill-details"><summary>Connection details</summary><p className="mono">{device.id}<small>{device.online ? 'Online' : 'Offline'} · {device.screen.kind} · Assignment {device.assignmentGeneration} · Last seen {device.lastSeenAt ? new Date(device.lastSeenAt).toLocaleString() : 'Never'}{device.revokedAt ? ' · Revoked' : ''}</small></p></details>{editable && !device.revokedAt && <button disabled={busy}><MerchantIcon name="save" />Save assignment</button>}{session.role === 'owner' && !device.revokedAt && <><button type="button" className="secondary" disabled={busy} onClick={() => void act(async () => { setCredential(await api(`/devices/${encodeURIComponent(device.id)}/credential`, {}, session.token)); })}><MerchantIcon name="arrow" />Set up connection</button><button type="button" className="secondary" disabled={busy} onClick={() => void act(async () => { await api(`/devices/${encodeURIComponent(device.id)}/credential`, undefined, session.token, 'DELETE'); setCredential(undefined); })}><MerchantIcon name="arrow" />Revoke credential</button><button type="button" className="secondary" disabled={busy} onClick={() => void act(async () => { await api(`/devices/${encodeURIComponent(device.id)}`, { revoked: true, expectedAssignmentGeneration: device.assignmentGeneration }, session.token, 'PATCH'); })}><MerchantIcon name="arrow" />Revoke device</button></>}</form>)}
    {credential && session.role === 'owner' && <section className="notice" aria-label="One-time device credential"><h3>One-time credential · keep private</h3><p>For coordinator-controlled provisioning only. Rotating invalidates the old credential. This value is not saved by the browser journal.</p><p className="mono">Device {credential.deviceId} · Auth generation {credential.authGeneration}</p><label>Private device credential<input type="password" readOnly value={credential.deviceToken} autoComplete="off" /></label><button onClick={() => void navigator.clipboard.writeText(credential.deviceToken).then(() => setMessage('Credential copied. Clear it after private provisioning.')).catch(() => setError('Clipboard unavailable; use the private credential field.'))}><MerchantIcon name="arrow" />Copy private credential</button><button className="secondary" onClick={() => setCredential(undefined)}><MerchantIcon name="trash" />Clear credential</button></section>}
    <h3>Register pairing</h3>{registers.filter(r => !r.retiredAt).map(register => <PairingRow key={`${register.id}:${register.pairingGeneration}`} register={register} devices={devices} registers={registers} editable={editable} busy={busy} save={deviceId => act(async () => { await api(`/registers/${encodeURIComponent(register.id)}/pairing`, { deviceId, expectedPairingGeneration: register.pairingGeneration }, session.token, 'PUT'); })} />)}
    </details>{error && <p className="error" role="alert">{error} · Refresh before retrying a generation conflict; no automatic overwrite.</p>}{message && <p role="status">{message}</p>}
  </section>;
}
function PairingRow({ register, devices, registers, editable, busy, save }: { register: Register; devices: Device[]; registers: Register[]; editable: boolean; busy: boolean; save(deviceId: string | null): Promise<void> }) {
  const [target, setTarget] = useState(register.deviceId ?? '');
  return <form className="registry-row" onSubmit={event => { event.preventDefault(); void save(target || null); }}><strong>{register.label}</strong><p>Current: {devices.find(d => d.id === register.deviceId)?.label ?? 'Unpaired'} · {register.targetOnline ? 'Online' : 'Offline / unpaired'}</p><label>POSClock<select aria-label="POSClock" value={target} disabled={!editable || busy} onChange={event => setTarget(event.target.value)}><option value="">Unpair</option>{devices.filter(d => !d.revokedAt).map(d => <option key={d.id} value={d.id} disabled={registers.some(r => r.id !== register.id && r.deviceId === d.id)}>{d.label} · {d.online ? 'Online' : 'Offline'} · {d.screen.kind}</option>)}</select></label><p className="notice">New orders go to {devices.find(d => d.id === target)?.label ?? 'no device'}. Current bills keep their original screen.</p>{editable && <button disabled={busy}><MerchantIcon name="link" />{target ? register.deviceId ? 'Save connection' : 'Connect POSClock' : 'Disconnect POSClock'}</button>}</form>;
}
