import React,{useEffect,useRef,useState} from 'react';
import type {Device,Table} from '../lib/table';
import MerchantIcon from './MerchantIcon';
import '../styles/shop-floor.css';
type Point={x:number;y:number};type Node=Point&{key:string;label:string;device?:Device;table?:Table};
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
export default function ShopFloor({merchantId,tables,devices,editable,assign}:{merchantId:string;tables:Table[];devices:Device[];editable:boolean;assign:(device:Device,tableId:string|null)=>Promise<void>}){
 const key='bitpos-floor-v1:'+merchantId;const [positions,setPositions]=useState<Record<string,Point>>({});const [selected,setSelected]=useState('');const [target,setTarget]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);const canvas=useRef<HTMLDivElement>(null);const drag=useRef<{key:string;startX:number;startY:number;point:Point;rect:DOMRect}|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(!raw)return;const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw Error();const clean:Record<string,Point>={};for(const [id,p]of Object.entries(parsed)){const v=p as Point;if(v&&Number.isFinite(v.x)&&Number.isFinite(v.y))clean[id]={x:clamp(v.x,10,90),y:clamp(v.y,20,85)};}setPositions(clean);}catch{setError('Layout storage unavailable. Positions will not be saved.');}},[key]);
 const activeTables=tables.filter(t=>!t.retiredAt),activeDevices=devices.filter(d=>!d.revokedAt);
 const nodes:Node[]=[...activeTables.map((t,i)=>({key:'t:'+t.id,label:t.label,table:t,x:26+i%3*27,y:38+Math.floor(i/3)%3*20})),...activeDevices.map((d,i)=>({key:'d:'+d.id,label:d.label,device:d,x:39+i%3*23,y:53+Math.floor(i/3)%2*22}))].map(n=>({...n,...positions[n.key]}));
 const node=nodes.find(n=>n.key===selected);
 function choose(n:Node){setSelected(n.key);setTarget(n.device?.tableId??'');setError('');}
 function savePosition(id:string,p:Point){setPositions(prior=>{const next={...prior,[id]:p};try{localStorage.setItem(key,JSON.stringify(next));setSaved(true);}catch{setError('Position could not be saved in this browser.');}return next;});}
 function pointerDown(e:React.PointerEvent<HTMLButtonElement>,n:Node){choose(n);if(!editable||saving||!canvas.current)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={key:n.key,startX:e.clientX,startY:e.clientY,point:{x:n.x,y:n.y},rect:canvas.current.getBoundingClientRect()};}
 function move(e:React.PointerEvent<HTMLButtonElement>){const d=drag.current;if(!d)return;const p={x:clamp(d.point.x+(e.clientX-d.startX)/d.rect.width*100,10,90),y:clamp(d.point.y+(e.clientY-d.startY)/d.rect.height*100,20,85)};setPositions(prior=>({...prior,[d.key]:p}));setSaved(false);}
 function finish(e:React.PointerEvent<HTMLButtonElement>){const d=drag.current;if(!d)return;drag.current=null;const p=positions[d.key]??d.point;savePosition(d.key,p);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);const n=nodes.find(n=>n.key===d.key);if(n?.device){const nearest=nodes.filter(n=>n.table).find(n=>Math.hypot(n.x-p.x,n.y-p.y)<12);if(nearest?.table)setTarget(nearest.table.id);}}
 async function saveAssignment(){if(!node?.device)return;setSaving(true);setError('');try{await assign(node.device,target||null);}catch(e){setError(e instanceof Error?e.message:'Could not save assignment.');}finally{setSaving(false);}}
 return <div className="shop-floor"><div className="floor-heading"><div><span className="floor-eyebrow">YOUR CAFE, CONNECTED</span><h2>Bring your space to life.</h2><p>Move tables and POSClocks. Make every seat a point of sale.</p></div><div className="floor-stats"><span><b>{activeTables.length}</b> tables</span><span><b>{activeDevices.filter(d=>d.online).length}/{activeDevices.length}</b> online</span></div></div>
 <div className="floor-layout"><div className="floor-scroll"><div className="floor-canvas" ref={canvas} aria-label="Interactive cafe floor plan"><div className="floor-window">W I N D O W</div><div className="floor-counter"><MerchantIcon name="cart"/><span>COFFEE BAR</span><i/><i/><i/></div><div className="floor-plant plant-a"><i/><i/><i/></div><div className="floor-plant plant-b"><i/><i/><i/></div><span className="floor-door">ENTRANCE</span>
 <svg className="floor-links" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{nodes.filter(n=>n.device?.tableId).map(n=>{const t=nodes.find(t=>t.table?.id===n.device?.tableId);return t?<line key={n.key} x1={n.x} y1={n.y} x2={t.x} y2={t.y}/>:null;})}</svg>
 {nodes.map(n=><button key={n.key} type="button" className={`floor-node ${n.device?'floor-device':'floor-table'} ${selected===n.key?'is-selected':''}`} style={{left:n.x+'%',top:n.y+'%'}} aria-label={`Move ${n.device?'POSClock':'table'}: ${n.label}`} aria-pressed={selected===n.key} onPointerDown={e=>pointerDown(e,n)} onPointerMove={move} onPointerUp={finish} onPointerCancel={()=>{const d=drag.current;drag.current=null;if(d)setPositions(prior=>({...prior,[d.key]:d.point}));}} onClick={e=>{if(e.detail===0)choose(n);}} onKeyDown={e=>{if(editable&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();savePosition(n.key,{x:clamp(n.x+(e.key==='ArrowRight'?2:e.key==='ArrowLeft'?-2:0),10,90),y:clamp(n.y+(e.key==='ArrowDown'?2:e.key==='ArrowUp'?-2:0),20,85)});}}}>
 {n.device?<><span className="floor-clock"><span className="clock-screen"><span>BitPOS</span><i/><small>{n.device.online?'ONLINE':'OFFLINE'}</small></span></span><span className={`floor-dot ${n.device.online?'is-online':''}`}/></>:<span className="floor-table-art"><i/><i/><i/><i/><span>{activeTables.findIndex(t=>t.id===n.table?.id)+1}</span></span>}<strong>{n.label}</strong>{n.device&&<small>{n.device.screen.kind==='idle'?'Available':'In use'}</small>}</button>)}
 {!nodes.length&&<div className="floor-empty">Your cafe starts here.<small>Add a table or POSClock below.</small></div>}</div></div>
 <aside className="floor-inspector"><span className="floor-eyebrow">{node?'SELECTED':'FLOOR PLAN'}</span><h3>{node?.device?'POSClock':node?.table?'Table':'A place for every connection.'}</h3><p>{node?.label??'Select a table or device to see its details.'}</p>{node?.device&&<><span className={`floor-status ${node.device.online?'is-online':''}`}>{node.device.online?'Online':'Offline'} · {node.device.screen.kind==='idle'?'Available':'In use'}</span><label>Serving table<select value={target} disabled={!editable||saving} onChange={e=>setTarget(e.target.value)}><option value="">Counter / unassigned</option>{activeTables.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label>{editable&&<button disabled={saving||target===(node.device.tableId??'')} onClick={()=>void saveAssignment()}><MerchantIcon name="save"/>{saving?'Saving…':'Save assignment'}</button>}</>}
 <div className="floor-help"><MerchantIcon name="menu"/><p>{editable?'Drag to arrange. Arrow keys also work.':'View your cafe layout.'}<small>{saved?'Position saved in this browser.':'Layout positions are saved in this browser.'} Table assignments are shared with your team.</small></p></div>{error&&<p role="alert" className="error">{error}</p>}</aside></div></div>;
}
