import {requestId} from '../lib/request-id';
import React,{useEffect,useRef,useState} from 'react';
import {api,ApiError,errorMessage} from '../lib/api';
import {formatMoney,lineTotal} from '../lib/money';
import {displayProduct,watchMenu,type Menu,type Product} from '../lib/menu';
import {freshGuest,restoreGuest,saveGuest,type GuestState,type GuestQuote} from '../lib/table-guest';
import type {OrderView} from '../../../../packages/contracts/src/index';
import {FrozenRouting,SettlementTrust} from './OrderBill';
import MerchantIcon, {LocaleFlag} from './MerchantIcon';
import '../styles/app.css';
import '../styles/customer-checkout.css';
import '../styles/table-menu.css';
type EntryMenu={tableLabel:string;menu:Menu;online:boolean;available:boolean};
type VisitView={kind:'order';order:OrderView}|{kind:'draft';expiresAt:string;online:boolean;available:boolean;quote:GuestQuote|null};
export default function TableMenu({entry}:{entry:string}){
 const [guest,setGuest]=useState<GuestState>();const [entryMenu,setEntryMenu]=useState<EntryMenu>();const [products,setProducts]=useState<Product[]>([]);const [valid,setValid]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [category,setCategory]=useState('');const [clock,setClock]=useState(Date.now());
 const [cartOpen,setCartOpen]=useState(false);const [language,setLanguage]=useState<'en'|'th'>('en');const [search,setSearch]=useState('');
 const acting=useRef(false);const current=useRef(guest);current.current=guest;const watch=useRef<ReturnType<typeof watchMenu>|undefined>(undefined);const base='/table/'+entry;
 function persist(next:GuestState){const saved=saveGuest(entry,next);current.current=saved;setGuest(saved);return saved;}
 async function action(fn:()=>Promise<void>){if(acting.current)return;acting.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(errorMessage(e));}finally{acting.current=false;setBusy(false);}}
 function own(v:GuestState){if(!v.visitToken)throw Error('Guest visit missing; nothing submitted.');return base+'/visit/'+v.visitToken;}
 function absorb(v:GuestState,state:VisitView){if(state.kind==='order')persist({...v,phase:'order',order:state.order});else if(v.phase!=='pending'&&state.quote&&Date.parse(state.quote.validUntil)>Date.now()&&state.quote.lines.length===v.items.length&&state.quote.lines.every(l=>v.items.some(i=>i.productId===l.productId&&i.qty===l.qty)))persist({...v,phase:'review',quote:state.quote});}
 useEffect(()=>{
  let active=true;let inFlight=false;let initial:GuestState;
  try{initial=restoreGuest(entry);persist(initial);}catch(e){setError(e instanceof Error?e.message:'Browser storage unavailable. New ordering is disabled to prevent duplicates.');return;}
  const watcher=watchMenu(async()=>{const result=await api<EntryMenu>(base);if(active)setEntryMenu(result);return result.menu;},(menu,leaseValid)=>{if(active){setProducts(menu.products.map(p=>displayProduct(p,leaseValid,menu.asOf)));setValid(leaseValid);}},e=>{if(active){setValid(false);setError(errorMessage(e));}});watch.current=watcher;
  async function recover(){const v=current.current;if(!v?.visitToken||inFlight||acting.current)return;inFlight=true;try{const result=await api<VisitView>(own(v));if(active&&current.current===v&&!acting.current)absorb(v,result);}catch(e){if(active)setError(errorMessage(e));}finally{inFlight=false;}}
  void recover();const poll=setInterval(()=>{setClock(Date.now());void recover();},3000);
  return()=>{active=false;clearInterval(poll);watcher.stop();watch.current=undefined;};
 },[entry]);
 async function review(){const v=current.current;if(!v||!v.items.length||v.phase==='pending'||v.phase==='order')throw Error('Cart cannot be reviewed while another outcome is unresolved.');let next:GuestState=v;
  if(!next.visitToken){const result=await api<{visitToken:string;state:VisitView}>(base+'/visit',{requestId:next.requestId});next=persist({...next,visitToken:result.visitToken});if(result.state.kind==='order'){absorb(next,result.state);return;}}
  const result=await api<{quote:GuestQuote}>(own(next)+'/quotes',{items:next.items});persist({...next,phase:'review',quote:result.quote});
 }
 async function submit(){let v=current.current;if(!v||!['review','pending'].includes(v.phase))throw Error('Review this cart first.');if(v.phase==='review'){
   if(Date.parse(v.quote.validUntil)<=Date.now())throw Error('Quote expired. Review again; no order submitted.');v=persist({...v,phase:'pending',request:{quoteId:v.quote.id,priceVersion:v.quote.priceVersion,idempotencyKey:requestId()}});
  }
  if(v.phase!=='pending')return;const pending=v;
  try{const result=await api<{kind:'order';order:OrderView}>(own(pending)+'/orders',pending.request);persist({...pending,phase:'order',order:result.order});location.assign(result.order.paymentUrl);}
  catch(e){if(e instanceof ApiError&&e.definiteRefusal){try{const state=await api<VisitView>(own(pending));if(state.kind==='order'){absorb(pending,state);return;}if(['QUOTE_EXPIRED','LEASE_EXPIRED','PRICE_VERSION_CHANGED','QUOTE_CHANGED','ASSIGNMENT_CHANGED','STOCK_UNAVAILABLE'].includes(e.code))persist({phase:'draft',items:pending.items,requestId:pending.requestId,visitToken:pending.visitToken});}catch{/* Unknown server outcome keeps the exact saved request. */}}throw e;}
 }
 const locked=!guest||busy||guest.phase==='pending'||guest.phase==='order';const selected=new Map(guest?.items.map(i=>[i.productId,i.qty]));const categories=[...new Set(products.map(p=>p.category).filter(Boolean))];const estimate=products.reduce((n,p)=>n+BigInt(p.unitPrice?.amountMinor??'0')*BigInt(selected.get(p.id)??0),0n);const quote=guest?.phase==='review'||guest?.phase==='pending'?guest.quote:null;const quoteCurrent=!!quote&&Date.parse(quote.validUntil)>clock&&valid&&quote.priceVersion===entryMenu?.menu.priceVersion&&quote.pricingRevision===entryMenu.menu.pricingRevision;
 function quantity(id:string,qty:number){const v=current.current;if(!v||locked)return;persist({phase:'draft',items:[...v.items.filter(i=>i.productId!==id),...(qty>0?[{productId:id,qty}]:[])],requestId:v.requestId,visitToken:v.visitToken});}
 const th=language==='th';const copy=(en:string,thai:string)=>th?thai:en;
 const itemCount=guest?.items.reduce((n,i)=>n+i.qty,0)??0;
 const total=entryMenu?.menu.currency?formatMoney({currency:entryMenu.menu.currency,decimals:entryMenu.menu.decimals!,amountMinor:estimate.toString()} as Parameters<typeof formatMoney>[0]):'…';
 const tableLabel=(entryMenu?.tableLabel??copy('Your table','โต๊ะของคุณ')).replace(/^Devnet demo table (\d+)$/,'Table $1');
 const shown=products.filter(p=>(!category||p.category===category)&&(!search||[p.name,p.nameEn,p.description].some(v=>v.toLowerCase().includes(search.toLowerCase()))));
 const photoNames:Record<string,string>={'Grilled Cheese Sandwich':'sandwich','Iced Latte':'iced-latte','Hot Chocolate':'hot-chocolate','Blueberry Muffin':'blueberry-muffin','Chocolate Brownie':'chocolate-brownie'};
 const photo=(p:Product)=>p.imageUrl||'/images/menu/'+(photoNames[p.nameEn]||p.nameEn.toLowerCase().replace(/ /g,'-'))+'.jpg';
 const categoryNames:Record<string,string>={'Coffee':'กาแฟ','Tea & Chocolate':'ชาและช็อกโกแลต','Bakery':'เบเกอรี่','Desserts':'ของหวาน','Savory':'อาหาร'};
 const categoryName=(c:string)=>th?(categoryNames[c]??c):c;
 function closeCart(){if(guest?.phase!=='pending')setCartOpen(false);}
 useEffect(()=>{if(!cartOpen)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&current.current?.phase!=='pending')setCartOpen(false);};window.addEventListener('keydown',escape);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',escape);};},[cartOpen]);
 function controls(p:Product,qty:number){return <div className="table-quantity">{qty>0&&<><button aria-label={'Decrease '+p.nameEn} disabled={locked} onClick={()=>void action(async()=>quantity(p.id,qty-1))}><MerchantIcon name="minus"/></button><output aria-label={p.nameEn+' quantity'}>{qty}</output></>}<button className="table-add" aria-label={'Increase '+p.nameEn} disabled={locked||!valid||!p.unitPrice||qty>=Math.min(100,p.available)} onClick={()=>void action(async()=>quantity(p.id,qty+1))}><MerchantIcon name="plus"/></button></div>;}
 const cartContent=<>
  {!guest?.items.length?<div className="table-empty"><MerchantIcon name="cart"/><p>{copy('Something delicious is waiting.','เลือกเมนูที่คุณชอบกันเลย')}</p><button className="table-primary" onClick={closeCart}>{copy('Explore the menu','ดูเมนู')}</button></div>:<>
   <ul className="table-cart-lines">{guest.items.map(i=>{const p=products.find(p=>p.id===i.productId);return <li key={i.productId}><img src={p?photo(p):'/images/menu/espresso.jpg'} alt=""/><div><strong>{p?(th?p.name:p.nameEn):copy('Item unavailable','เมนูไม่พร้อม')}</strong><span>{p?.unitPrice?formatMoney(p.unitPrice):'—'}</span></div>{p&&controls(p,i.qty)}</li>;})}</ul>
   {quote?<section className="table-review" aria-label="Canonical guest review"><p className="table-review-title"><MerchantIcon name="check"/>{copy('Your bill is ready','บิลของคุณพร้อมแล้ว')}</p><ul className="checkout-lines">{quote.lines.map(l=><li key={l.productId}><span>{l.qty} × {th?l.name:l.nameEn}</span><strong>{formatMoney(lineTotal(l))}</strong></li>)}</ul><div className="table-cart-total"><span>{copy('Total','ยอดรวม')}</span><strong>{formatMoney(quote.total)}</strong></div><p className="table-fee-note">{copy('Pay with USDG · Network fee covered by the cafe','จ่ายด้วย USDG · ร้านออกค่าธรรมเนียมให้')}</p>{!quoteCurrent&&<p className="notice">{copy('This bill has expired. Review your order again.','บิลหมดอายุ กรุณาตรวจสอบอีกครั้ง')}</p>}<details className="table-order-details"><summary>{copy('Payment details','รายละเอียดการชำระ')}</summary><FrozenRouting authority={quote.authority}/><SettlementTrust settlement={quote.settlement}/><small>{copy('Valid until','ใช้ได้ถึง')} {new Date(quote.validUntil).toLocaleTimeString()}</small></details></section>:<div className="table-cart-total"><span>{copy('Estimated total','ยอดประมาณ')}</span><strong>{total}</strong></div>}
   {guest?.phase==='pending'?<><p className="notice" role="status">{copy('We’re checking your order. Please don’t order again.','กำลังตรวจสอบออเดอร์ กรุณาอย่าสั่งซ้ำ')}</p><button className="table-primary" disabled={busy} onClick={()=>void action(submit)}>{copy('Check my order','ตรวจสอบออเดอร์')}</button></>:<>
    {guest?.phase==='review'&&quoteCurrent?<button className="table-primary" disabled={busy||!entryMenu?.online} onClick={()=>void action(submit)}><MerchantIcon name="check"/>{busy?copy('Please wait…','กรุณารอสักครู่…'):copy('Confirm order & pay','ยืนยันออเดอร์และชำระ')}</button>:<button className="table-primary" disabled={locked||!valid||!entryMenu?.online||!guest?.items.length} onClick={()=>void action(review)}><MerchantIcon name="receipt"/>{busy?copy('Preparing your bill…','กำลังเตรียมบิล…'):copy('Review order','ตรวจสอบออเดอร์')}</button>}
    <button className="table-text-button" disabled={busy} onClick={closeCart}>{copy('Add something else','เลือกเมนูเพิ่ม')}</button><button className="table-text-button table-clear" disabled={locked||!guest?.items.length} onClick={()=>void action(async()=>{const v=current.current!;if(v.visitToken)await api(own(v)+'/release',{});persist({phase:'draft',items:[],requestId:v.requestId,visitToken:v.visitToken});})}><MerchantIcon name="trash"/>{copy('Clear cart','ล้างตะกร้า')}</button>
   </>}
  </>}
 </>;
 return <main className="customer-checkout table-menu" lang={language}><div className="checkout-shell">
  <header className="checkout-header"><a href={base} aria-label="BitPOS table menu"><img src="/images/bitpos-logo.png" alt="BitPOS" width="132" height="44"/></a><div className="table-header-actions"><span className="checkout-network">Devnet</span><button className="table-language" aria-label={th?'Switch to English':'เปลี่ยนเป็นภาษาไทย'} onClick={()=>setLanguage(th?'en':'th')}><LocaleFlag language={th?'en':'th'}/></button></div></header>
  <section className="table-heading"><div className="table-heading-meta"><span>{entryMenu?.menu.merchant.name??'BitPOS Cafe'}</span><span className="table-location"><MerchantIcon name="menu"/>{tableLabel}</span></div><h1>{copy('Coffee first.','กาแฟแก้วโปรด')}<br/><em>{copy('Good moments.','กับช่วงเวลาดี ๆ')}</em></h1><p>{copy('Freshly made. Delivered to your table.','เลือกเมนูที่ชอบ แล้วรอรับที่โต๊ะได้เลย')}</p><img className="table-hero-cup" src="/images/menu/latte.jpg" alt=""/></section>
  {error&&<div className="error table-notice" role="alert"><span>{error}</span><button aria-label={copy('Dismiss notice','ปิดข้อความ')} onClick={()=>setError('')}><MerchantIcon name="close"/></button></div>}
  {guest?.phase==='order'?<section className="checkout-card checkout-content table-order-ready"><div className="table-order-check"><MerchantIcon name={guest.order.status==='PAID'?'check':'receipt'}/></div><h2>{guest.order.status==='PAID'?copy('Thank you!','ขอบคุณค่ะ'):copy('Your order is ready','ออเดอร์ของคุณพร้อมแล้ว')}</h2><p>{tableLabel} · #{guest.order.id.slice(0,8)}</p><ul className="checkout-lines">{guest.order.pricing.lines.map(l=><li key={l.productId}><span>{l.qty} × {th?l.name:l.nameEn}</span><strong>{formatMoney(lineTotal(l))}</strong></li>)}</ul><div className="table-cart-total"><span>{copy('Total','ยอดรวม')}</span><strong>{formatMoney(guest.order.pricing.total)}</strong></div><a className="table-primary" href={guest.order.paymentUrl}>{guest.order.status==='PAID'?copy('View receipt','ดูใบเสร็จ'):copy('Continue to payment','ไปชำระเงิน')}<MerchantIcon name="arrow"/></a><details className="table-order-details"><summary>{copy('Order details','รายละเอียดออเดอร์')}</summary><FrozenRouting authority={guest.order.authority}/></details></section>:<>
   {!entryMenu?.online&&entryMenu&&<p className="notice table-notice" role="status">{copy('The table display is reconnecting. You can still browse.','จอกำลังเชื่อมต่อใหม่ สามารถดูเมนูได้ก่อน')}</p>}{entryMenu&&!entryMenu.available&&guest?.phase!=='review'&&guest?.phase!=='pending'&&<p className="notice table-notice" role="status">{copy('This table has an active order. Please wait or ask the cafe team.','โต๊ะนี้มีออเดอร์อยู่ กรุณารอสักครู่หรือสอบถามพนักงาน')}</p>}
   <div className="table-menu-heading"><h2>{copy('Our menu','เมนูของเรา')}</h2><span>{copy('Made with love','ทำด้วยความใส่ใจ')}</span></div><label className="table-search"><span className="sr-only">{copy('Search menu','ค้นหาเมนู')}</span><input type="search" placeholder={copy('Find your favourite…','ค้นหาเมนูที่ชอบ…')} value={search} onChange={e=>setSearch(e.target.value)}/></label>
   <nav className="table-categories" aria-label="Menu categories"><button aria-pressed={!category} onClick={()=>setCategory('')}>{copy('All','ทั้งหมด')}</button>{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{categoryName(c)}</button>)}</nav>
   {!entryMenu?<div className="table-loading" role="status">{copy('Loading the menu…','กำลังโหลดเมนู…')}</div>:<section className="table-products" aria-label="Cafe menu">{shown.map(p=>{const qty=selected.get(p.id)??0;return <article key={p.id} className={'table-product'+(qty?' is-selected':'')+(p.available<=0?' is-sold-out':'')}><div className="table-product-image"><img src={photo(p)} alt={th?p.name:p.nameEn} loading="lazy" onError={e=>{e.currentTarget.style.visibility='hidden';}}/>{p.promotion&&<span className="table-discount">{p.promotion.discount.kind==='percent'?'-'+p.promotion.discount.percent+'%':copy('Special offer','ราคาพิเศษ')}</span>}</div><div className="table-product-content"><small>{categoryName(p.category)}</small><h3>{th?p.name:p.nameEn}</h3><p>{p.description}</p><div className="table-product-bottom"><div className="table-product-price"><strong>{p.unitPrice?formatMoney(p.unitPrice):'—'}</strong>{p.promotion&&p.basePrice&&<del>{formatMoney(p.basePrice)}</del>}{p.available<=0&&<span>{copy('Sold out','หมดชั่วคราว')}</span>}</div>{controls(p,qty)}</div></div></article>;})}</section>}
   {entryMenu&&!shown.length&&<p className="table-loading">{copy('No matches. Try another favourite.','ไม่พบเมนู ลองค้นหาใหม่อีกครั้ง')}</p>}
   <footer className="table-footer"><span>BitPOS · {copy('Order. Relax. Enjoy.','สั่งง่าย อร่อยที่โต๊ะ')}</span><small>{copy('Demo checkout uses test USDG on Solana devnet.','เดโมนี้ใช้ test USDG บน Solana devnet')}</small><button className="table-text-button" disabled={busy} onClick={()=>void watch.current?.refresh()}><MerchantIcon name="refresh"/>{copy('Refresh menu','รีเฟรชเมนู')}</button></footer>
  </>}
 </div>
 {guest?.phase!=='order'&&itemCount>0&&<div className="table-cart-dock"><button className="table-cart-trigger" onClick={()=>setCartOpen(true)} aria-haspopup="dialog"><span className="table-cart-count">{itemCount}</span><span>{copy('View your order','ดูออเดอร์')}<small>{copy('Review before paying','ตรวจสอบก่อนชำระเงิน')}</small></span><strong>{quoteCurrent&&quote?formatMoney(quote.total):total}</strong><MerchantIcon name="arrow"/></button></div>}
 {cartOpen&&guest?.phase!=='order'&&<div className="table-sheet-shade" onClick={e=>{if(e.target===e.currentTarget)closeCart();}}><section className="table-sheet" role="dialog" aria-modal="true" aria-label="Your cart" tabIndex={-1} ref={node=>{if(node&&!node.contains(document.activeElement))node.focus();}} onKeyDown={e=>{if(e.key!=='Tab')return;const nodes=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],summary');const first=nodes[0],last=nodes[nodes.length-1];if(!first)return;if(e.shiftKey&&(document.activeElement===first||document.activeElement===e.currentTarget)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}><div className="table-sheet-head"><div><p>{tableLabel}</p><h2>{copy('Your order','ออเดอร์ของคุณ')}</h2></div><button className="table-sheet-close" aria-label="Close cart" disabled={guest?.phase==='pending'} onClick={closeCart}><MerchantIcon name="close"/></button></div>{error&&<p className="error" role="alert">{error}</p>}{cartContent}</section></div>}
 </main>;
}
