#!/usr/bin/env python3
"""Generate bounded RGB565 SD photos from the existing licensed cafe catalog.
Run with local/toolchains/serial-env/bin/python. Never downloads source images.
"""
import argparse
import array
import hashlib
import json
from pathlib import Path
import re
import sys
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]
WIDTH, HEIGHT = 480, 200
PHOTO_BYTES = WIDTH * HEIGHT * 2

def digest(data):
    return hashlib.sha256(data).hexdigest()

def replace_if_changed(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_bytes() == data:
        return
    temporary = path.with_name(path.name + '.tmp')
    temporary.write_bytes(data)
    temporary.replace(path)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--manifest', type=Path)
    parser.add_argument('--header', type=Path)
    parser.add_argument('--previews', type=Path)
    args = parser.parse_args()
    catalog_bytes = (ROOT / 'data/cafe-catalog.json').read_bytes()
    catalog = json.loads(catalog_bytes)
    products = catalog['products']
    if not 1 <= len(products) <= 12:
        raise ValueError('Menu asset bound is twelve real catalog photos')
    public = (ROOT / 'apps/web/public').resolve()
    prepared, records, seen = [], [], set()
    for product in products:
        url = product['imageUrl']
        match = re.fullmatch(r'/images/menu/([a-z0-9-]{1,40})\.jpg', url)
        if not match:
            raise ValueError('Catalog image is outside the local photo allowlist')
        filename = match[1] + '.rgb565'
        if filename in seen:
            raise ValueError('Duplicate menu bitmap filename')
        seen.add(filename)
        source = (public / url.lstrip('/')).resolve()
        source.relative_to(public)
        source_bytes = source.read_bytes()
        if digest(source_bytes) != product['photo']['sha256']:
            raise ValueError('Catalog photo hash mismatch: ' + filename)
        with Image.open(source) as image:
            if image.size != (product['photo']['width'], product['photo']['height']):
                raise ValueError('Catalog photo dimensions mismatch: ' + filename)
            cropped = ImageOps.fit(image.convert('RGB'), (WIDTH, HEIGHT), method=Image.Resampling.LANCZOS)
        pixels = array.array('H', (((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3) for r, g, b in cropped.getdata()))
        if pixels.itemsize != 2:
            raise ValueError('RGB565 requires sixteen-bit storage')
        if sys.byteorder != 'little':
            pixels.byteswap()
        bitmap = pixels.tobytes()
        if len(bitmap) != PHOTO_BYTES:
            raise ValueError('Incorrect bounded bitmap length')
        prepared.append((filename, bitmap, cropped))
        records.append({'catalogKey': product['key'], 'imageUrl': url, 'file': filename,
                        'bytes': len(bitmap), 'sha256': digest(bitmap),
                        'sourceSha256': digest(source_bytes), 'sourcePhoto': product['photo']})
    manifest = {'schemaVersion': 1, 'version': 'bitpos-menu-v1',
                'sdRoot': '/sdcard/bitpos/menu/v1', 'width': WIDTH, 'height': HEIGHT,
                'pixelFormat': 'RGB565_LE', 'maxPhotos': 12,
                'catalogSha256': digest(catalog_bytes),
                'pricing': 'Database canonical quotes are authoritative; assets contain no prices or offers',
                'assets': records}
    encoded = (json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + '\n').encode()
    for filename, bitmap, cropped in prepared:
        replace_if_changed(args.output / filename, bitmap)
        if args.previews:
            args.previews.mkdir(parents=True, exist_ok=True)
            cropped.save(args.previews / (filename.removesuffix('.rgb565') + '.png'))
    manifest_path = args.manifest or args.output / 'manifest.json'
    replace_if_changed(manifest_path, encoded)
    if args.header:
        entries = '\n'.join('    {"' + item['file'] + '", "' + item['sha256'] + '"},' for item in records)
        header = ('/* Generated by tools/runtime/prepare-menu-assets.py; licensed source photo provenance in manifest. */\n'
                  '#pragma once\n'
                  '#define BITPOS_MENU_PHOTO_WIDTH 480\n#define BITPOS_MENU_PHOTO_HEIGHT 200\n'
                  '#define BITPOS_MENU_PHOTO_BYTES 192000\n#define BITPOS_MENU_ASSET_COUNT ' + str(len(records)) + '\n'
                  'typedef struct { const char *file; const char *sha256; } bitpos_menu_asset_t;\n'
                  'static const bitpos_menu_asset_t bitpos_menu_assets[BITPOS_MENU_ASSET_COUNT] = {\n' + entries + '\n};\n').encode()
        replace_if_changed(args.header, header)
    print(json.dumps({'assets': len(records), 'bytes_each': PHOTO_BYTES,
                      'total_bytes': len(records) * PHOTO_BYTES, 'manifest_sha256': digest(encoded),
                      'origin': 'existing_hash_verified_real_cafe_catalog_photos',
                      'offers_in_assets': False}))

if __name__ == '__main__':
    main()
