/* Generated by tools/runtime/prepare-menu-assets.py; licensed source photo provenance in manifest. */
#pragma once
#define BITPOS_MENU_PHOTO_WIDTH 480
#define BITPOS_MENU_PHOTO_HEIGHT 200
#define BITPOS_MENU_PHOTO_BYTES 192000
#define BITPOS_MENU_ASSET_COUNT 12
typedef struct { const char *file; const char *sha256; } bitpos_menu_asset_t;
static const bitpos_menu_asset_t bitpos_menu_assets[BITPOS_MENU_ASSET_COUNT] = {
    {"espresso.rgb565", "277a09d5c212585b0922315ade916b9f7c4a86b2e71142b3b776009350e3d008"},
    {"americano.rgb565", "79b36497dba504bb30784de2b84ca02581ef5407be195343cf648551781803ed"},
    {"latte.rgb565", "5b7bf770beffafd1ee3323d9920baa5f8c34144b82904327f6da42b3fdb20d7c"},
    {"iced-latte.rgb565", "3aa2d4133320e503f58de9408ec790296af7334eb827c347b2f4f0faf635db5d"},
    {"cappuccino.rgb565", "b4175e864d373d3a0e1ef5ecc84f2fbff4716030588dc858c7d5b2a48432a881"},
    {"matcha.rgb565", "9b3eb30098e47396718752a0b26a18e79011bd5767bb56255aca7c9112bbb47c"},
    {"hot-chocolate.rgb565", "3c1d4c4e4b790fde52575bc01b5e99bd96efd729093b801ccd4d5386780fe83b"},
    {"croissant.rgb565", "595b283e41fb17f57176faf654b1c77ed73ed98850352138092cab27edd13b8a"},
    {"blueberry-muffin.rgb565", "4268a21ef08b4c4cb55cea9e1dde1a64198430c2ee0b546977836846a43558c9"},
    {"chocolate-brownie.rgb565", "c3f28722ded981d8a850bf38ea5ee3f9f7d766aa4722acdf12566a2445125a1c"},
    {"cheesecake.rgb565", "9b6eb26aeadff8f86aa9f5ea19cd959abf967cdfd737999537fb7f350f93afde"},
    {"sandwich.rgb565", "8f7c08539f542bdf0b32d0ab31f40b8181d430130d2cc4e23d653cf4e7de335a"},
};
