#!/usr/bin/env python3
"""Bake BitPOS Segment 64: original beveled seven-segment digits, no font dependency.

Run from any directory: python3 device/firmware/main/bitpos_clock_generate.py
This generator and its output are BitPOS-authored; they are not DSEG7 or a copy
of its outlines. Only ASCII '-' and '0'..'9' are mapped. UI colon is native dots.
The committed 1bpp font is a device bitmap, not a browser font.
"""
from pathlib import Path

WIDTH, HEIGHT = 36, 64
# a,b,c,d,e,f,g; clockwise from top, with the middle last.
SEGMENTS = [
    [(5, 0), (31, 0), (35, 4), (31, 8), (5, 8), (1, 4)],
    [(32, 6), (36, 10), (36, 27), (32, 31), (28, 27), (28, 10)],
    [(32, 33), (36, 37), (36, 54), (32, 58), (28, 54), (28, 37)],
    [(5, 56), (31, 56), (35, 60), (31, 64), (5, 64), (1, 60)],
    [(4, 33), (8, 37), (8, 54), (4, 58), (0, 54), (0, 37)],
    [(4, 6), (8, 10), (8, 27), (4, 31), (0, 27), (0, 10)],
    [(5, 28), (31, 28), (35, 32), (31, 36), (5, 36), (1, 32)],
]
MAPPING = ['g', 'abcdef', 'bc', 'abdeg', 'abcdg', 'bcfg', 'acdfg',
           'acdefg', 'abc', 'abcdefg', 'abcdfg']


def inside(x, y, polygon):
    """Convex polygon coverage at integer pixel centers, using doubled coords."""
    cross = []
    for (ax, ay), (bx, by) in zip(polygon, polygon[1:] + polygon[:1]):
        cross.append((bx - ax) * (y - 2 * ay) - (by - ay) * (x - 2 * ax))
    return all(value >= 0 for value in cross) or all(value <= 0 for value in cross)


bitmap, descriptors = [], ['    {0}, /* reserved glyph zero */']
for letters in MAPPING:
    start = len(bitmap)
    bits = [int(any(inside(2 * x + 1, 2 * y + 1, SEGMENTS[ord(s) - ord('a')])
                    for s in letters)) for y in range(HEIGHT) for x in range(WIDTH)]
    for offset in range(0, len(bits), 8):
        value = 0
        for bit in bits[offset:offset + 8]:
            value = (value << 1) | bit
        bitmap.append(value)
    descriptors.append(f'    {{.bitmap_index={start}, .adv_w={42 * 16}, '
                       f'.box_w={WIDTH}, .box_h={HEIGHT}, .ofs_x=0, .ofs_y=0}},')
rows = ['    ' + ', '.join(f'0x{value:02x}' for value in bitmap[i:i + 16]) + ','
        for i in range(0, len(bitmap), 16)]
source = '''/* BitPOS Segment 64. Generated by bitpos_clock_generate.py; original geometry.
 * Not DSEG7. ASCII '-' and digits only. 1bpp, uncompressed, no external assets.
 */
#include "lvgl.h"
static const uint8_t glyph_bitmap[] = {
''' + '\n'.join(rows) + '''
};
static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
''' + '\n'.join(descriptors) + '''
};
static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start=45, .range_length=1, .glyph_id_start=1,
     .type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start=48, .range_length=10, .glyph_id_start=2,
     .type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
};
static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap=glyph_bitmap, .glyph_dsc=glyph_dsc, .cmaps=cmaps,
    .cmap_num=2, .bpp=1, .bitmap_format=0,
};
const lv_font_t bitpos_clock_64 = {
    .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,
    .line_height=64, .base_line=0, .subpx=LV_FONT_SUBPX_NONE,
    .dsc=&font_dsc,
};
'''
Path(__file__).with_name('bitpos_clock_64.c').write_text(source)
