idf_component_register(SRCS "main.c" "bitpos_table.c" "bitpos_font_20.c" "bitpos_clock_64.c" "bitpos_logo.c" "bitpos_media.c" "bitpos_audio.c" "bitpos_probe.c" INCLUDE_DIRS "." REQUIRES board_bsp display_engine esp_wifi nvs_flash esp_event esp_netif esp_websocket_client esp_http_client json esp_driver_i2s esp_driver_sdmmc esp_driver_usb_serial_jtag esp_timer esp_psram fatfs sdmmc lwip esp_app_format mbedtls)
