CREATE SCHEMA IF NOT EXISTS bitpos;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
SET search_path TO bitpos, public;
CREATE TABLE merchants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,treasury text NOT NULL,version int NOT NULL DEFAULT 1);
CREATE TABLE members(user_id uuid NOT NULL,merchant_id uuid NOT NULL REFERENCES merchants,role text NOT NULL CHECK(role IN ('owner','manager','staff')),PRIMARY KEY(user_id,merchant_id));
CREATE TABLE sessions(token_hash text PRIMARY KEY,user_id uuid NOT NULL,merchant_id uuid NOT NULL REFERENCES merchants,role text NOT NULL,expires_at timestamptz NOT NULL);
CREATE TABLE customers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL REFERENCES merchants,name text NOT NULL DEFAULT '',phone text NOT NULL DEFAULT '',email text NOT NULL DEFAULT '',notes text NOT NULL DEFAULT '',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(merchant_id,id));
CREATE TABLE customer_wallets(merchant_id uuid NOT NULL,customer_id uuid NOT NULL,address text NOT NULL,chain text NOT NULL DEFAULT 'solana:devnet',verified_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(merchant_id,chain,address),FOREIGN KEY(merchant_id,customer_id) REFERENCES customers(merchant_id,id));
CREATE TABLE products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL REFERENCES merchants,name text NOT NULL,name_en text NOT NULL,emoji text NOT NULL,price_minor bigint NOT NULL CHECK(price_minor>0),stock int NOT NULL CHECK(stock>=0),reserved int NOT NULL DEFAULT 0 CHECK(reserved>=0 AND reserved<=stock),UNIQUE(merchant_id,id));
CREATE TABLE orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL REFERENCES merchants,customer_id uuid NOT NULL,access_token text NOT NULL UNIQUE,idempotency_key text NOT NULL,request_hash text NOT NULL,status text NOT NULL DEFAULT 'AWAITING_WALLET',version int NOT NULL DEFAULT 1,thb_minor bigint NOT NULL,usdg_minor bigint NOT NULL,treasury text NOT NULL,quote_expires_at timestamptz NOT NULL,payer text,terminal_id text NOT NULL DEFAULT 'terminal-1',created_at timestamptz NOT NULL DEFAULT now(),paid_at timestamptz,UNIQUE(merchant_id,id),UNIQUE(merchant_id,idempotency_key),FOREIGN KEY(merchant_id,customer_id) REFERENCES customers(merchant_id,id));
CREATE TABLE order_items(order_id uuid NOT NULL,merchant_id uuid NOT NULL,product_id uuid NOT NULL,name text NOT NULL,name_en text NOT NULL,qty int NOT NULL CHECK(qty>0),unit_minor bigint NOT NULL,PRIMARY KEY(order_id,product_id),FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id),FOREIGN KEY(merchant_id,product_id) REFERENCES products(merchant_id,id));
CREATE TABLE challenges(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL,order_id uuid NOT NULL,address text NOT NULL,message text NOT NULL,expires_at timestamptz NOT NULL,used_at timestamptz,FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id));
CREATE TABLE payment_attempts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL,order_id uuid NOT NULL,reference text NOT NULL UNIQUE,payer text NOT NULL,recipient text NOT NULL,amount_minor bigint NOT NULL,mint text NOT NULL,token_program text NOT NULL,transaction_base64 text,signature text UNIQUE,blockhash text,last_valid_height bigint,status text NOT NULL DEFAULT 'BUILDING',fee_lamports bigint NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),submitted_at timestamptz,error text,FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id));
CREATE UNIQUE INDEX one_live_attempt ON payment_attempts(order_id) WHERE status IN ('BUILDING','READY','SUBMITTING','SUBMITTED','CONFIRMED');
CREATE TABLE payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL,order_id uuid NOT NULL,attempt_id uuid NOT NULL UNIQUE REFERENCES payment_attempts,signature text NOT NULL UNIQUE,amount_minor bigint NOT NULL,state text NOT NULL CHECK(state IN ('SETTLED','RECOVERY')),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id));
CREATE TABLE outbox_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL REFERENCES merchants,order_id uuid NOT NULL REFERENCES orders,order_version int NOT NULL,type text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE device_deliveries(event_id uuid NOT NULL REFERENCES outbox_events,terminal_id text NOT NULL,sent_at timestamptz,rendered_at timestamptz,latency_ms int,PRIMARY KEY(event_id,terminal_id));
CREATE TABLE audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL REFERENCES merchants,actor text NOT NULL,action text NOT NULL,subject text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE refunds(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL,order_id uuid NOT NULL REFERENCES orders,payment_id uuid NOT NULL UNIQUE REFERENCES payments,status text NOT NULL DEFAULT 'REQUESTED',signature text UNIQUE,error text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE loyalty_ledger(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_id uuid NOT NULL,customer_id uuid NOT NULL,order_id uuid NOT NULL UNIQUE REFERENCES orders,points int NOT NULL,FOREIGN KEY(merchant_id,customer_id) REFERENCES customers(merchant_id,id));
GRANT USAGE ON SCHEMA bitpos TO bitpos_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA bitpos TO bitpos_app;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA bitpos TO bitpos_app;
-- Backend transactions set the tenant only after session/capability validation.
DO $$ DECLARE t text; BEGIN
FOREACH t IN ARRAY ARRAY['customers','customer_wallets','products','orders','order_items','challenges','payment_attempts','payments','outbox_events','audit_logs','refunds','loyalty_ledger'] LOOP
 EXECUTE format('ALTER TABLE bitpos.%I ENABLE ROW LEVEL SECURITY',t);
 EXECUTE format('CREATE POLICY tenant_access ON bitpos.%I FOR ALL TO bitpos_app USING (merchant_id::text = current_setting(''bitpos.merchant'',true)) WITH CHECK (merchant_id::text = current_setting(''bitpos.merchant'',true))',t);
END LOOP; END $$;
-- No anon/authenticated/service-role table grants: browser never bypasses API authorization.
