SET search_path TO bitpos, public;
ALTER TABLE orders ADD COLUMN authority_version smallint CHECK(authority_version IS NULL OR authority_version=2), ADD COLUMN recovery_resolved_at timestamptz;
ALTER TABLE orders DROP CONSTRAINT orders_merchant_id_idempotency_key_key;
CREATE UNIQUE INDEX legacy_order_key ON orders(merchant_id,idempotency_key) WHERE authority_version IS NULL;
ALTER TABLE orders ALTER COLUMN thb_minor DROP NOT NULL, ALTER COLUMN terminal_id DROP NOT NULL, ALTER COLUMN terminal_id DROP DEFAULT;
ALTER TABLE orders ADD CHECK((authority_version IS NULL AND thb_minor IS NOT NULL AND terminal_id IS NOT NULL) OR (authority_version=2 AND thb_minor IS NULL AND terminal_id IS NULL));
CREATE TABLE merchant_tables(merchant_id uuid NOT NULL REFERENCES merchants,id uuid NOT NULL DEFAULT gen_random_uuid(),label text NOT NULL CHECK(octet_length(label) BETWEEN 1 AND 95),retired_at timestamptz,PRIMARY KEY(merchant_id,id));
CREATE TABLE devices(merchant_id uuid NOT NULL REFERENCES merchants,id uuid NOT NULL DEFAULT gen_random_uuid(),label text NOT NULL CHECK(octet_length(label) BETWEEN 1 AND 95),table_id uuid,assignment_generation bigint NOT NULL DEFAULT 1 CHECK(assignment_generation>0),auth_generation bigint NOT NULL DEFAULT 1 CHECK(auth_generation>0),revoked_at timestamptz,PRIMARY KEY(merchant_id,id),FOREIGN KEY(merchant_id,table_id) REFERENCES merchant_tables(merchant_id,id));
CREATE TABLE registers(merchant_id uuid NOT NULL REFERENCES merchants,id uuid NOT NULL DEFAULT gen_random_uuid(),label text NOT NULL CHECK(octet_length(label) BETWEEN 1 AND 95),paired_device_id uuid,pairing_generation bigint NOT NULL DEFAULT 1 CHECK(pairing_generation>0),retired_at timestamptz,PRIMARY KEY(merchant_id,id),UNIQUE(merchant_id,paired_device_id),FOREIGN KEY(merchant_id,paired_device_id) REFERENCES devices(merchant_id,id));
CREATE TABLE device_credentials(token_hash text PRIMARY KEY CHECK(token_hash ~ '^[0-9a-f]{64}$'),merchant_id uuid NOT NULL,device_id uuid NOT NULL,auth_generation bigint NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),revoked_at timestamptz,FOREIGN KEY(merchant_id,device_id) REFERENCES devices(merchant_id,id));
CREATE UNIQUE INDEX one_device_credential ON device_credentials(merchant_id,device_id) WHERE revoked_at IS NULL;
CREATE TABLE device_presence(merchant_id uuid NOT NULL,device_id uuid NOT NULL,connection_generation bigint NOT NULL DEFAULT 0 CHECK(connection_generation>=0),connection_id uuid,connected_until timestamptz,last_seen_at timestamptz,PRIMARY KEY(merchant_id,device_id),FOREIGN KEY(merchant_id,device_id) REFERENCES devices(merchant_id,id));
CREATE TABLE device_sessions(merchant_id uuid NOT NULL,id uuid NOT NULL,device_id uuid NOT NULL,assignment_generation bigint NOT NULL,cart_version bigint NOT NULL DEFAULT 0 CHECK(cart_version>=0),cart jsonb NOT NULL DEFAULT '[]'::jsonb,review_quote_id uuid,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),ended_at timestamptz,PRIMARY KEY(merchant_id,id),UNIQUE(merchant_id,device_id,id),FOREIGN KEY(merchant_id,device_id) REFERENCES devices(merchant_id,id));
CREATE TABLE device_screen_state(merchant_id uuid NOT NULL,device_id uuid NOT NULL,screen_generation bigint NOT NULL DEFAULT 1 CHECK(screen_generation>0),kind text NOT NULL DEFAULT 'idle' CHECK(kind IN ('idle','cart','order')),session_id uuid,order_id uuid,lease_until timestamptz,PRIMARY KEY(merchant_id,device_id),FOREIGN KEY(merchant_id,device_id) REFERENCES devices(merchant_id,id),FOREIGN KEY(merchant_id,device_id,session_id) REFERENCES device_sessions(merchant_id,device_id,id),FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id),CHECK((kind='idle' AND session_id IS NULL AND order_id IS NULL AND lease_until IS NULL) OR (kind='cart' AND session_id IS NOT NULL AND order_id IS NULL AND lease_until IS NOT NULL) OR (kind='order' AND session_id IS NULL AND order_id IS NOT NULL AND lease_until IS NULL)));
CREATE TABLE catalog_price_versions(merchant_id uuid NOT NULL REFERENCES merchants,id uuid NOT NULL DEFAULT gen_random_uuid(),currency text NOT NULL CHECK(currency IN ('THB','USD','USDG')),decimals smallint NOT NULL,configured_by uuid,configured_at timestamptz NOT NULL DEFAULT clock_timestamp(),provenance text NOT NULL CHECK(provenance IN ('legacy_thb','owner_configured','demo_configured')),demo_label text,quote_policy text CHECK(quote_policy IN ('USD_CENTS_TO_USDG_1_TO_1','USDG_RAW_IDENTITY')),PRIMARY KEY(merchant_id,id),CHECK((currency IN ('THB','USD') AND decimals=2) OR (currency='USDG' AND decimals=6)),CHECK(provenance<>'demo_configured' OR octet_length(demo_label) BETWEEN 1 AND 95),CHECK((currency='THB' AND quote_policy IS NULL) OR (currency='USD' AND quote_policy='USD_CENTS_TO_USDG_1_TO_1') OR (currency='USDG' AND quote_policy='USDG_RAW_IDENTITY')));
CREATE TABLE catalog_prices(merchant_id uuid NOT NULL,price_version_id uuid NOT NULL,product_id uuid NOT NULL,unit_minor bigint NOT NULL CHECK(unit_minor>0),PRIMARY KEY(merchant_id,price_version_id,product_id),UNIQUE(merchant_id,price_version_id,product_id,unit_minor),FOREIGN KEY(merchant_id,price_version_id) REFERENCES catalog_price_versions(merchant_id,id),FOREIGN KEY(merchant_id,product_id) REFERENCES products(merchant_id,id));
CREATE TABLE merchant_pricing(merchant_id uuid PRIMARY KEY REFERENCES merchants,active_price_version_id uuid NOT NULL,revision bigint NOT NULL CHECK(revision>0),FOREIGN KEY(merchant_id,active_price_version_id) REFERENCES catalog_price_versions(merchant_id,id));
CREATE TABLE versioned_product_offers(merchant_id uuid NOT NULL,product_id uuid NOT NULL,price_version_id uuid NOT NULL,revision bigint NOT NULL CHECK(revision>0),enabled boolean NOT NULL,kind text NOT NULL CHECK(kind IN ('amount','percent')),amount_minor bigint,percent smallint,base_minor bigint NOT NULL,current_minor bigint NOT NULL,expires_at timestamptz NOT NULL CHECK(isfinite(expires_at)),PRIMARY KEY(merchant_id,price_version_id,product_id,revision),FOREIGN KEY(merchant_id,price_version_id,product_id,base_minor) REFERENCES catalog_prices(merchant_id,price_version_id,product_id,unit_minor),CHECK(current_minor>0 AND current_minor<base_minor),CHECK((kind='amount' AND percent IS NULL AND amount_minor>0 AND current_minor=base_minor-amount_minor) OR (kind='percent' AND amount_minor IS NULL AND percent BETWEEN 1 AND 99 AND current_minor=base_minor-floor(base_minor::numeric*percent/100)::bigint)));
-- Snapshot only: legacy THB remains historical, never activates new checkout.
INSERT INTO catalog_price_versions(merchant_id,currency,decimals,provenance) SELECT id,'THB',2,'legacy_thb' FROM merchants;
INSERT INTO catalog_prices SELECT v.merchant_id,v.id,p.id,p.price_minor FROM catalog_price_versions v JOIN products p ON p.merchant_id=v.merchant_id WHERE v.provenance='legacy_thb';
INSERT INTO versioned_product_offers SELECT o.merchant_id,o.product_id,v.id,o.revision,o.enabled,o.kind,o.amount_minor,o.percent,o.base_minor,o.current_minor,o.expires_at FROM product_offers o JOIN catalog_price_versions v ON v.merchant_id=o.merchant_id AND v.provenance='legacy_thb' JOIN catalog_prices p ON p.merchant_id=o.merchant_id AND p.price_version_id=v.id AND p.product_id=o.product_id AND p.unit_minor=o.base_minor;
CREATE TABLE order_quotes(merchant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),origin_kind text NOT NULL CHECK(origin_kind IN ('register','device')),origin_id uuid NOT NULL,source_register_id uuid,source_device_id uuid,session_id uuid,cart_version bigint,price_version_id uuid NOT NULL,pricing_revision bigint NOT NULL,cart jsonb NOT NULL,lines jsonb NOT NULL,total_minor bigint NOT NULL CHECK(total_minor>0),usdg_minor bigint NOT NULL CHECK(usdg_minor BETWEEN 1 AND 999999999999999999),treasury text NOT NULL,settlement jsonb NOT NULL,authority jsonb NOT NULL,request_hash text NOT NULL,quoted_at timestamptz NOT NULL,valid_until timestamptz NOT NULL,PRIMARY KEY(merchant_id,id),FOREIGN KEY(merchant_id,price_version_id) REFERENCES catalog_price_versions(merchant_id,id),FOREIGN KEY(merchant_id,source_register_id) REFERENCES registers(merchant_id,id),FOREIGN KEY(merchant_id,source_device_id) REFERENCES devices(merchant_id,id),FOREIGN KEY(merchant_id,source_device_id,session_id) REFERENCES device_sessions(merchant_id,device_id,id),CHECK((origin_kind='register' AND source_register_id=origin_id AND source_device_id IS NULL AND session_id IS NULL AND cart_version IS NULL) OR (origin_kind='device' AND source_device_id=origin_id AND source_register_id IS NULL AND session_id IS NOT NULL AND cart_version IS NOT NULL)),CHECK(valid_until>quoted_at));
ALTER TABLE device_sessions ADD FOREIGN KEY(merchant_id,review_quote_id) REFERENCES order_quotes(merchant_id,id);
CREATE TABLE order_authority(merchant_id uuid NOT NULL,order_id uuid NOT NULL,source_kind text NOT NULL CHECK(source_kind IN ('register','device')),source_register_id uuid,source_device_id uuid,source_label_snapshot text NOT NULL,target_device_id uuid NOT NULL,target_assignment_generation bigint NOT NULL,creation_pairing_generation bigint,screen_generation bigint NOT NULL,serving_kind text NOT NULL CHECK(serving_kind IN ('table','counter','takeaway')),serving_table_id uuid,serving_label_snapshot text NOT NULL,quote_id uuid NOT NULL,price_version_id uuid NOT NULL,catalog_currency text NOT NULL,catalog_decimals smallint NOT NULL,total_minor bigint NOT NULL,settlement jsonb NOT NULL,PRIMARY KEY(merchant_id,order_id),UNIQUE(merchant_id,order_id,target_device_id),FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id),FOREIGN KEY(merchant_id,source_register_id) REFERENCES registers(merchant_id,id),FOREIGN KEY(merchant_id,source_device_id) REFERENCES devices(merchant_id,id),FOREIGN KEY(merchant_id,target_device_id) REFERENCES devices(merchant_id,id),FOREIGN KEY(merchant_id,serving_table_id) REFERENCES merchant_tables(merchant_id,id),FOREIGN KEY(merchant_id,quote_id) REFERENCES order_quotes(merchant_id,id),FOREIGN KEY(merchant_id,price_version_id) REFERENCES catalog_price_versions(merchant_id,id),CHECK((source_kind='register' AND source_register_id IS NOT NULL AND source_device_id IS NULL AND creation_pairing_generation IS NOT NULL) OR (source_kind='device' AND source_device_id IS NOT NULL AND source_register_id IS NULL AND creation_pairing_generation IS NULL)),CHECK((serving_kind='table' AND serving_table_id IS NOT NULL) OR (serving_kind<>'table' AND serving_table_id IS NULL)));
CREATE TABLE order_line_prices(merchant_id uuid NOT NULL,order_id uuid NOT NULL,product_id uuid NOT NULL,price_version_id uuid NOT NULL,base_minor bigint NOT NULL,offer_revision bigint,currency text NOT NULL,decimals smallint NOT NULL,PRIMARY KEY(merchant_id,order_id,product_id),FOREIGN KEY(merchant_id,order_id) REFERENCES order_authority(merchant_id,order_id),FOREIGN KEY(merchant_id,price_version_id,product_id) REFERENCES catalog_prices(merchant_id,price_version_id,product_id),FOREIGN KEY(merchant_id,price_version_id,product_id,offer_revision) REFERENCES versioned_product_offers(merchant_id,price_version_id,product_id,revision));
CREATE TABLE order_submissions(merchant_id uuid NOT NULL,origin_kind text NOT NULL CHECK(origin_kind IN ('register','device')),origin_id uuid NOT NULL,source_register_id uuid,source_device_id uuid,idempotency_key text NOT NULL CHECK(octet_length(idempotency_key) BETWEEN 1 AND 128),request_hash text NOT NULL,order_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(merchant_id,origin_kind,origin_id,idempotency_key),UNIQUE(merchant_id,order_id),FOREIGN KEY(merchant_id,order_id) REFERENCES order_authority(merchant_id,order_id),FOREIGN KEY(merchant_id,source_register_id) REFERENCES registers(merchant_id,id),FOREIGN KEY(merchant_id,source_device_id) REFERENCES devices(merchant_id,id),CHECK((origin_kind='register' AND source_register_id=origin_id AND source_device_id IS NULL) OR (origin_kind='device' AND source_device_id=origin_id AND source_register_id IS NULL)));
CREATE TABLE device_command_results(merchant_id uuid NOT NULL,device_id uuid NOT NULL,request_id uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(merchant_id,device_id,request_id),FOREIGN KEY(merchant_id,device_id) REFERENCES devices(merchant_id,id));
CREATE TABLE device_event_counters(merchant_id uuid NOT NULL,device_id uuid NOT NULL,device_seq bigint NOT NULL DEFAULT 0,PRIMARY KEY(merchant_id,device_id),FOREIGN KEY(merchant_id,device_id) REFERENCES devices(merchant_id,id));
ALTER TABLE outbox_events ADD UNIQUE(merchant_id,id), ADD FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id), ADD COLUMN target_device_id uuid, ADD COLUMN target_assignment_generation bigint, ADD COLUMN screen_generation bigint, ADD COLUMN device_seq bigint, ADD FOREIGN KEY(merchant_id,target_device_id) REFERENCES devices(merchant_id,id), ADD UNIQUE(merchant_id,id,target_device_id,device_seq), ADD CHECK((target_device_id IS NULL AND target_assignment_generation IS NULL AND screen_generation IS NULL AND device_seq IS NULL) OR (target_device_id IS NOT NULL AND target_assignment_generation>0 AND screen_generation>0 AND device_seq>0));
ALTER TABLE outbox_events ALTER COLUMN order_id DROP NOT NULL, ALTER COLUMN order_version DROP NOT NULL;
CREATE INDEX device_outbox_stream ON outbox_events(merchant_id,target_device_id,device_seq);
CREATE TABLE device_event_deliveries(merchant_id uuid NOT NULL,device_id uuid NOT NULL,event_id uuid NOT NULL,device_seq bigint NOT NULL,connection_generation bigint NOT NULL,status text NOT NULL DEFAULT 'sent' CHECK(status IN ('sent','rendered','superseded')),sent_at timestamptz NOT NULL DEFAULT clock_timestamp(),rendered_at timestamptz,latency_ms bigint,PRIMARY KEY(merchant_id,device_id,event_id,connection_generation),FOREIGN KEY(merchant_id,event_id,device_id,device_seq) REFERENCES outbox_events(merchant_id,id,target_device_id,device_seq));
CREATE TABLE device_sound_effects(merchant_id uuid NOT NULL,device_id uuid NOT NULL,order_id uuid NOT NULL,paid_version int NOT NULL,effect_id uuid NOT NULL DEFAULT gen_random_uuid(),consumed_at timestamptz,PRIMARY KEY(merchant_id,device_id,order_id,paid_version),UNIQUE(effect_id),FOREIGN KEY(merchant_id,order_id,device_id) REFERENCES order_authority(merchant_id,order_id,target_device_id));
-- Existing delivery evidence acquires tenant isolation without changing payloads.
ALTER TABLE device_deliveries ADD COLUMN merchant_id uuid;
UPDATE device_deliveries d SET merchant_id=e.merchant_id FROM outbox_events e WHERE e.id=d.event_id;
ALTER TABLE device_deliveries ALTER COLUMN merchant_id SET NOT NULL, ADD FOREIGN KEY(merchant_id,event_id) REFERENCES outbox_events(merchant_id,id);
ALTER TABLE payment_attempts ADD UNIQUE(merchant_id,id), ADD UNIQUE(merchant_id,order_id,id);
ALTER TABLE payments ADD UNIQUE(merchant_id,id), ADD FOREIGN KEY(merchant_id,order_id,attempt_id) REFERENCES payment_attempts(merchant_id,order_id,id);
ALTER TABLE refunds ADD FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id), ADD FOREIGN KEY(merchant_id,payment_id) REFERENCES payments(merchant_id,id);
ALTER TABLE loyalty_ledger ADD FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id);
ALTER TABLE sponsor_orders ADD FOREIGN KEY(merchant_id,order_id) REFERENCES orders(merchant_id,id);
CREATE FUNCTION immutable_authority_row() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable authority record' USING ERRCODE='23514'; END $$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['catalog_price_versions','catalog_prices','versioned_product_offers','order_quotes','order_authority','order_line_prices','order_submissions','device_command_results'] LOOP EXECUTE format('CREATE TRIGGER immutable_row BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION immutable_authority_row()',t); END LOOP; END $$;
CREATE FUNCTION guard_order_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF ROW(NEW.merchant_id,NEW.access_token,NEW.idempotency_key,NEW.request_hash,NEW.authority_version,NEW.thb_minor,NEW.usdg_minor,NEW.treasury,NEW.quote_expires_at,NEW.terminal_id) IS DISTINCT FROM ROW(OLD.merchant_id,OLD.access_token,OLD.idempotency_key,OLD.request_hash,OLD.authority_version,OLD.thb_minor,OLD.usdg_minor,OLD.treasury,OLD.quote_expires_at,OLD.terminal_id) THEN RAISE EXCEPTION 'immutable order quote' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER immutable_order BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION guard_order_immutable();
CREATE FUNCTION guard_v2_order() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.authority_version=2 AND (NOT EXISTS(SELECT 1 FROM order_authority a JOIN order_quotes q ON q.merchant_id=a.merchant_id AND q.id=a.quote_id JOIN order_submissions s ON s.merchant_id=a.merchant_id AND s.order_id=a.order_id WHERE a.merchant_id=NEW.merchant_id AND a.order_id=NEW.id AND q.usdg_minor=NEW.usdg_minor AND q.treasury=NEW.treasury AND q.price_version_id=a.price_version_id AND q.total_minor=a.total_minor AND s.request_hash=NEW.request_hash) OR EXISTS(SELECT 1 FROM order_items i WHERE i.merchant_id=NEW.merchant_id AND i.order_id=NEW.id AND NOT EXISTS(SELECT 1 FROM order_line_prices l WHERE l.merchant_id=i.merchant_id AND l.order_id=i.order_id AND l.product_id=i.product_id))) THEN RAISE EXCEPTION 'incomplete versioned order' USING ERRCODE='23514'; END IF; RETURN NULL; END $$;
CREATE CONSTRAINT TRIGGER v2_order_complete AFTER INSERT ON orders DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION guard_v2_order();
CREATE FUNCTION guard_screen_target() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.kind='order' AND NOT EXISTS(SELECT 1 FROM order_authority WHERE merchant_id=NEW.merchant_id AND order_id=NEW.order_id AND target_device_id=NEW.device_id AND screen_generation=NEW.screen_generation) THEN RAISE EXCEPTION 'wrong screen target' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER screen_target BEFORE INSERT OR UPDATE ON device_screen_state FOR EACH ROW EXECUTE FUNCTION guard_screen_target();
CREATE FUNCTION bitpos.resolve_device(credential_hash text) RETURNS TABLE(merchant_id uuid,device_id uuid,auth_generation bigint) LANGUAGE sql SECURITY DEFINER SET search_path=bitpos,pg_temp AS $$ SELECT c.merchant_id,c.device_id,c.auth_generation FROM device_credentials c JOIN devices d ON d.merchant_id=c.merchant_id AND d.id=c.device_id WHERE c.token_hash=credential_hash AND c.revoked_at IS NULL AND d.revoked_at IS NULL AND c.auth_generation=d.auth_generation $$;
REVOKE ALL ON FUNCTION bitpos.resolve_device(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION bitpos.resolve_device(text) TO bitpos_app;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['merchant_tables','devices','registers','device_credentials','device_presence','device_sessions','device_screen_state','catalog_price_versions','catalog_prices','merchant_pricing','versioned_product_offers','order_quotes','order_authority','order_line_prices','order_submissions','device_command_results','device_event_counters','device_event_deliveries','device_sound_effects','device_deliveries'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('CREATE POLICY tenant_access ON %I FOR ALL TO bitpos_app USING(merchant_id::text=current_setting(''bitpos.merchant'',true)) WITH CHECK(merchant_id::text=current_setting(''bitpos.merchant'',true))',t); EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON %I TO bitpos_app',t); END LOOP; END $$;
-- JSON is an immutable wire snapshot, not a way around relational tenant keys.
ALTER TABLE order_quotes
 ADD COLUMN target_device_id uuid GENERATED ALWAYS AS ((authority->'target'->>'deviceId')::uuid) STORED,
 ADD COLUMN serving_table_id uuid GENERATED ALWAYS AS ((authority->'serving'->>'tableId')::uuid) STORED,
 ADD FOREIGN KEY(merchant_id,target_device_id) REFERENCES devices(merchant_id,id),
 ADD FOREIGN KEY(merchant_id,serving_table_id) REFERENCES merchant_tables(merchant_id,id),
 ADD CHECK(target_device_id IS NOT NULL),
 ADD CHECK((origin_kind='register' AND source_register_id IS NOT NULL) OR (origin_kind='device' AND source_device_id IS NOT NULL));
ALTER TABLE order_submissions ADD CHECK((origin_kind='register' AND source_register_id IS NOT NULL) OR (origin_kind='device' AND source_device_id IS NOT NULL));
ALTER TABLE catalog_price_versions ADD UNIQUE(merchant_id,id,currency,decimals);
ALTER TABLE order_authority ADD FOREIGN KEY(merchant_id,price_version_id,catalog_currency,catalog_decimals) REFERENCES catalog_price_versions(merchant_id,id,currency,decimals),
 ADD CHECK(target_assignment_generation>0 AND screen_generation>0 AND total_minor>0),
 ADD CHECK(octet_length(source_label_snapshot) BETWEEN 1 AND 95 AND octet_length(serving_label_snapshot) BETWEEN 1 AND 95);
CREATE FUNCTION guard_authority_quote() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE q order_quotes; BEGIN
 SELECT * INTO STRICT q FROM order_quotes WHERE merchant_id=NEW.merchant_id AND id=NEW.quote_id;
 IF q.origin_kind<>NEW.source_kind OR q.origin_id<>coalesce(NEW.source_register_id,NEW.source_device_id)
 OR q.price_version_id<>NEW.price_version_id OR q.total_minor<>NEW.total_minor OR q.settlement<>NEW.settlement
 OR q.target_device_id<>NEW.target_device_id
 OR (q.authority->'target'->>'assignmentGeneration')::bigint<>NEW.target_assignment_generation
 OR q.authority->'source'->>'label'<>NEW.source_label_snapshot
 OR q.authority->'serving'->>'kind'<>NEW.serving_kind
 OR q.serving_table_id IS DISTINCT FROM NEW.serving_table_id
 OR q.authority->'serving'->>'label'<>NEW.serving_label_snapshot
 OR (q.authority->>'pairingGeneration')::bigint IS DISTINCT FROM NEW.creation_pairing_generation THEN
 RAISE EXCEPTION 'quote authority mismatch' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER authority_quote BEFORE INSERT ON order_authority FOR EACH ROW EXECUTE FUNCTION guard_authority_quote();
CREATE FUNCTION guard_outbox_target() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.target_device_id IS NOT NULL AND NEW.type='ORDER' AND NOT EXISTS(
 SELECT 1 FROM order_authority a WHERE a.merchant_id=NEW.merchant_id AND a.order_id=NEW.order_id
 AND a.target_device_id=NEW.target_device_id AND a.target_assignment_generation=NEW.target_assignment_generation
 AND a.screen_generation=NEW.screen_generation) THEN RAISE EXCEPTION 'wrong event target' USING ERRCODE='23514'; END IF;
 RETURN NEW; END $$;
CREATE TRIGGER outbox_target BEFORE INSERT ON outbox_events FOR EACH ROW EXECUTE FUNCTION guard_outbox_target();
CREATE TRIGGER immutable_bill BEFORE UPDATE OR DELETE ON order_items FOR EACH ROW EXECUTE FUNCTION immutable_authority_row();
CREATE TRIGGER immutable_event BEFORE UPDATE OR DELETE ON outbox_events FOR EACH ROW EXECUTE FUNCTION immutable_authority_row();
ALTER TABLE device_sessions ADD CHECK(jsonb_typeof(cart)='array' AND jsonb_array_length(cart)<=50);
ALTER TABLE order_quotes ADD CHECK(jsonb_typeof(cart)='array' AND jsonb_array_length(cart) BETWEEN 1 AND 50 AND jsonb_typeof(lines)='array' AND jsonb_array_length(lines)=jsonb_array_length(cart));
ALTER TABLE catalog_price_versions ADD CHECK((provenance='legacy_thb')=(currency='THB')), ADD CHECK(provenance<>'demo_configured' OR demo_label IS NOT NULL);
ALTER TABLE order_items ADD UNIQUE(merchant_id,order_id,product_id);
ALTER TABLE order_line_prices ADD FOREIGN KEY(merchant_id,order_id,product_id) REFERENCES order_items(merchant_id,order_id,product_id);
CREATE FUNCTION guard_active_prices() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM catalog_price_versions WHERE merchant_id=NEW.merchant_id AND id=NEW.active_price_version_id AND currency IN ('USD','USDG') AND provenance<>'legacy_thb') THEN RAISE EXCEPTION 'legacy prices cannot activate new checkout' USING ERRCODE='23514'; END IF;
 RETURN NEW; END $$;
CREATE TRIGGER active_prices BEFORE INSERT OR UPDATE ON merchant_pricing FOR EACH ROW EXECUTE FUNCTION guard_active_prices();
CREATE FUNCTION guard_quote_money() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v catalog_price_versions; amount numeric; BEGIN
 SELECT * INTO STRICT v FROM catalog_price_versions WHERE merchant_id=NEW.merchant_id AND id=NEW.price_version_id;
 SELECT sum((l->'unitPrice'->>'amountMinor')::numeric*(l->>'qty')::numeric) INTO amount FROM jsonb_array_elements(NEW.lines) l;
 IF v.currency NOT IN ('USD','USDG') OR amount<>NEW.total_minor
 OR NEW.usdg_minor::numeric<>NEW.total_minor::numeric*(CASE WHEN v.currency='USD' THEN 10000 ELSE 1 END)
 OR NEW.settlement IS DISTINCT FROM jsonb_build_object('currency','USDG','decimals',6,'amountMinor',NEW.usdg_minor::text,'network','solana:devnet','genesisHash','EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG','mint','4F6PM96JJxngmHnZLBh9n58RH4aTVNWvDs2nuwrT5BP7','tokenProgram','TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb','testToken',true,'recipient',NEW.treasury,'sponsor','merchant_funded')
 OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.lines) l WHERE l->'unitPrice'->>'currency'<>v.currency OR (l->'unitPrice'->>'decimals')::int<>v.decimals OR l->>'priceVersion'<>v.id::text OR (l->>'qty')::int NOT BETWEEN 1 AND 100 OR (l->'unitPrice'->>'amountMinor')::bigint<=0)
 THEN RAISE EXCEPTION 'invalid canonical quote money' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER quote_money BEFORE INSERT ON order_quotes FOR EACH ROW EXECUTE FUNCTION guard_quote_money();
CREATE FUNCTION guard_bill_snapshot() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF EXISTS(SELECT 1 FROM orders WHERE merchant_id=NEW.merchant_id AND id=NEW.order_id AND authority_version=2)
 AND NOT EXISTS(SELECT 1 FROM order_authority a JOIN order_quotes q ON q.merchant_id=a.merchant_id AND q.id=a.quote_id CROSS JOIN LATERAL jsonb_array_elements(q.lines) l WHERE a.merchant_id=NEW.merchant_id AND a.order_id=NEW.order_id AND l->>'productId'=NEW.product_id::text AND l->>'name'=NEW.name AND l->>'nameEn'=NEW.name_en AND (l->>'qty')::int=NEW.qty AND (l->'unitPrice'->>'amountMinor')::bigint=NEW.unit_minor)
 THEN RAISE EXCEPTION 'bill differs from immutable review' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER bill_snapshot BEFORE INSERT ON order_items FOR EACH ROW EXECUTE FUNCTION guard_bill_snapshot();
CREATE FUNCTION guard_bill_complete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.authority_version=2 AND NOT EXISTS(
 SELECT 1 FROM order_authority a JOIN order_quotes q ON q.merchant_id=a.merchant_id AND q.id=a.quote_id
 JOIN order_submissions s ON s.merchant_id=a.merchant_id AND s.order_id=a.order_id
 WHERE a.merchant_id=NEW.merchant_id AND a.order_id=NEW.id AND s.origin_kind=a.source_kind
 AND s.origin_id=coalesce(a.source_register_id,a.source_device_id)
 AND (SELECT count(*) FROM order_items i WHERE i.merchant_id=a.merchant_id AND i.order_id=a.order_id)=jsonb_array_length(q.lines))
 THEN RAISE EXCEPTION 'incomplete bill or submission origin' USING ERRCODE='23514'; END IF; RETURN NULL; END $$;
CREATE CONSTRAINT TRIGGER bill_complete AFTER INSERT ON orders DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION guard_bill_complete();
CREATE FUNCTION guard_line_price_snapshot() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM order_authority a JOIN order_quotes q ON q.merchant_id=a.merchant_id AND q.id=a.quote_id CROSS JOIN LATERAL jsonb_array_elements(q.lines) l
 WHERE a.merchant_id=NEW.merchant_id AND a.order_id=NEW.order_id AND l->>'productId'=NEW.product_id::text
 AND q.price_version_id=NEW.price_version_id AND (l->'basePrice'->>'amountMinor')::bigint=NEW.base_minor
 AND (l->'promotion'->>'revision')::bigint IS NOT DISTINCT FROM NEW.offer_revision
 AND l->'unitPrice'->>'currency'=NEW.currency AND (l->'unitPrice'->>'decimals')::int=NEW.decimals)
 THEN RAISE EXCEPTION 'line price provenance mismatch' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER line_price_snapshot BEFORE INSERT ON order_line_prices FOR EACH ROW EXECUTE FUNCTION guard_line_price_snapshot();
ALTER TABLE catalog_price_versions ADD CHECK(currency='THB' OR quote_policy IS NOT NULL);
CREATE FUNCTION guard_attempt_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF ROW(NEW.merchant_id,NEW.order_id,NEW.reference,NEW.payer,NEW.recipient,NEW.amount_minor,NEW.mint,NEW.token_program)
 IS DISTINCT FROM ROW(OLD.merchant_id,OLD.order_id,OLD.reference,OLD.payer,OLD.recipient,OLD.amount_minor,OLD.mint,OLD.token_program)
 OR (OLD.transaction_base64 IS NOT NULL AND ROW(NEW.transaction_base64,NEW.blockhash,NEW.last_valid_height)
 IS DISTINCT FROM ROW(OLD.transaction_base64,OLD.blockhash,OLD.last_valid_height))
 OR (OLD.signature IS NOT NULL AND NEW.signature IS DISTINCT FROM OLD.signature)
 OR (OLD.signed_base64 IS NOT NULL AND NEW.signed_base64 IS DISTINCT FROM OLD.signed_base64)
 THEN RAISE EXCEPTION 'immutable payment attempt proof' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER attempt_proof BEFORE UPDATE ON payment_attempts FOR EACH ROW EXECUTE FUNCTION guard_attempt_immutable();
